Repository micrometer-metrics/micrometer, pull requests merged in 2019-12, with the labels that each got.

#1726 Replace deprecated DoubleFormat.decimalOrWhole() usages
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceTimeSeries.java
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioMeterRegistry.java
  implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: polish

#1727 Add tests for HibernateMetrics.monitor() with SessionFactory
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateMetricsTest.java
Labels: type: task

#1728 Clean up compile warnings
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-ganglia/src/test/java/io/micrometer/ganglia/GangliaMeterRegistryCompatibilityTest.java
  micrometer-core/src/test/java/io/micrometer/core/ipc/http/RequestTest.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/properties/StepRegistryPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/properties/StepRegistryPropertiesTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/web/client/RestTemplateExchangeTagsTest.java
Labels: polish

#1729 Clean up compile warnings in 1.3.x branch
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryCompatibilityTest.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchUtilsTest.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/test/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistryTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: polish

#1730 Add compiler arguments for compile warnings
  build.gradle
Labels: polish

#1733 Clean up compile warnings in master
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/OkHttpSender.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MeterFilterTest.java
Labels: polish

#1731 Add illegal import check for Java6Assertions
  config/checkstyle/checkstyle.xml
Labels: type: task

#1742 Avoid substring allocation where possible
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java
Labels: polish

#1744 Fix Javadoc warnings and errors
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/AbstractInternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLoggerFactory.java
Labels: polish

#1747 Clean up compile warnings
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
Labels: type: task

#1740 Update io.dropwizard.metrics:metrics-graphite to 4.1+
  implementations/micrometer-registry-graphite/build.gradle
Labels: enhancement, registry: graphite

#1750 Truncate tag values > 1024 for Stackdriver
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverNamingConvention.java
Labels: bug, registry: stackdriver

#1753 Pin kafka-clients version to 2.3.1
  micrometer-core/build.gradle
Labels: type: task

#1589 Add Compilation JVM metric binder
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/CompilationMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/CompilationMetricsTest.java
Labels: enhancement, spring-boot change

#1749 native-image.properties that adds the shaded artifact pcollections to initialize-at-build-time.
  micrometer-core/src/main/resources/META-INF/native-image/io.micrometer.shaded.org.pcollections/pcollections/native-image.properties
Labels: enhancement
