Repository micrometer-metrics/micrometer, pull requests merged in 2019-06, with the labels that each got.

#1446 Use name of Meter.Id.Type for metric_type in InfluxDB's Line Protocol
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java
  implementations/micrometer-registry-influx/src/test/java/io/micrometer/influx/InfluxMeterRegistryTest.java
Labels: release notes

#1440 Add Javadoc since to TomcatMetrics.setJmxDomain()
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
Labels: polish

#1448 Use latest.release version for junit-jupiter-params dependency
  implementations/micrometer-registry-statsd/build.gradle
Labels: polish

#1419 Add an empty constructor to TimedAspect
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
Labels: enhancement

#1436 Append a delimiter at the end of all BufferingFlux messages
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/BufferingFlux.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/internal/BufferingFluxTest.java
Labels: bug, registry: statsd

#1376 Batching logic was not following New Relic expectations
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryUtilsTest.java
Labels: bug, registry: new relic

#1362 Polish NamingConvention
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
Labels: polish

#1450 Add Timer count to Stackdriver registry
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: registry: stackdriver

#1453 Prevent race condition when updating tags for StatsD Datadog flavor
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java
Labels: bug, registry: statsd

#1412 Polish NamingConvention
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
Labels: polish

#804 Polish AbstractTimeWindowHistogram.takeValueSnapshot()
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/HistogramSnapshot.java
Labels: polish

#1392 Backporting changes for issue #1282
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MeterRegistryConfigurer.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MeterRegistryPostProcessor.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MetricsAutoConfiguration.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/CompositeRegistryDoubleCountingTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/SingleRegistryDoubleCountingTest.java
Labels: boot2-change

#866 Add constants for base units
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/EhCache2Metrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/HazelcastCacheMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/DatabaseTableMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyStatisticsMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/composite/CompositeMeterRegistryTest.java
Labels: polish

#673 Rename DoubleFormat.decimalOrWhole()
  implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/AtlasMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/HistogramGauges.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/DoubleFormat.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/DoubleFormatTest.java
Labels: type: task

#1381 Allow infinities for Amazon CloudWatch again
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchUtils.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
Labels: bug, registry: cloudwatch

#1383 Drop custom meters' non-finite measurements for remaining meter registries
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
  implementations/micrometer-registry-appoptics/src/test/java/io/micrometer/appoptics/AppOpticsMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioMeterRegistry.java
  implementations/micrometer-registry-humio/src/test/java/io/micrometer/humio/HumioMeterRegistryTest.java
  implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosMeterRegistry.java
  implementations/micrometer-registry-kairos/src/test/java/io/micrometer/kairos/KairosMeterRegistryTest.java
Labels: bug, registry: appoptics, registry: humio, registry: kairos

#1337 Disable other histogram metrics when sending Wavefront Histograms
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontDistributionSummary.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontTimer.java
Labels: registry: wavefront

#1315 Wavefront cumulative values
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontDistributionSummary.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeTimer.java
Labels: enhancement, registry: wavefront, release notes

#1229 Add Hystrix thread pool metric publisher
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisher.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherThreadPool.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherThreadPoolTest.java
Labels: enhancement

#1404 When no event occurs don't sent aggregated metrics to cloudwatch
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
Labels: registry: cloudwatch

#1449 AppOptics Implementation - Set metric time to clock time.
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsConfig.java
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
  implementations/micrometer-registry-appoptics/src/test/java/io/micrometer/appoptics/AppOpticsMeterRegistryTest.java
Labels: enhancement, registry: appoptics

#1459 Move GcGenerationAge into JvmGcMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
Labels: type: task

#1463 Polish JvmGcMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
Labels: polish

#1470 Handle when additivity for the root logger is false
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/Log4j2Metrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/logging/Log4j2MetricsTest.java
  micrometer-core/src/test/resources/binder/logging/log4j2-root-logger-additivity-false.xml
Labels: bug

#1467 Make JvmGcMetrics no-op when unsupported
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
Labels: enhancement

#1476 Remove String concatenation in BufferingFlux.create()
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/BufferingFlux.java
Labels: polish

#1477 Polish BufferingFluxTest.bufferMessagesCanBeAppended()
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/internal/BufferingFluxTest.java
Labels: polish

#1351 Add mongodb driver metrics
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListenerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListenerTest.java
Labels: boot2-change, enhancement

#1004 Add Proxy option to HttpUrlConnectionSender
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/HttpUrlConnectionSender.java
  samples/micrometer-samples-boot1/build.gradle
Labels: enhancement

#1286 Added instrumentation for Apache HttpComponents HttpRequestExecutor
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: enhancement

#1332 Add option to override the current index name format
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
Labels: registry: elastic

#1330 Add option to create custom timestamp value
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
Labels: registry: elastic

#1336 Made the id printing in LoggingMeterRegistry configurable
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/logging/LoggingMeterRegistryTest.java
Labels: enhancement
