Repository micrometer-metrics/micrometer, pull requests merged in 2019-09, with the labels that each got.

#1581 Upgrade to Gradle Wrapper 5.6.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1592 Polish ReactorNettySender
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/ReactorNettySender.java
Labels: polish

#1601 Update tests to align with changes from PushGateway
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/prometheus/PrometheusMetricsExportAutoConfigurationTest.java
Labels: type: task

#1585 Fix NewRelicMeterRegistry.writeMeter() publishing duplicate keys/metrics
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: bug, registry: new relic

#1588 Add support for categorical "MicrometerSample" eventType to publish New Relic metrics.
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: enhancement, registry: new relic, release notes

#1524 [Stackdriver] Allow to set custom MonitoredResouce
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: registry: stackdriver

#1544 Move to new Humio structered API.
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioConfig.java
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioMeterRegistry.java
  implementations/micrometer-registry-humio/src/test/java/io/micrometer/humio/HumioMeterRegistryTest.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/humio/HumioPropertiesConfigAdapter.java
Labels: enhancement, registry: humio, spring-boot change

#1577 Fix typo
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
Labels: polish

#1475 Make PushMeterRegistry work without slf4j-api
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/AbstractInternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/FormattingTuple.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLogLevel.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/LocationAwareSlf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/MessageFormatter.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/package-info.java
Labels: release notes, type: task

#1580 Fix reporting of counter metrics to Azure Monitor
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
Labels: bug, registry: azure monitor

#1582 Make value function defensive for exceptions in DefaultGauge
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java
Labels: bug

#1532 Handle exception for gauge value function in DropwizardMeterRegistry
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java
Labels: bug, registry: graphite, registry: jmx

#1610 Apply illegal import Checkstyle rule for SLF4J
  config/checkstyle/checkstyle-suppressions.xml
  config/checkstyle/checkstyle.xml
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommand.java
Labels: type: task
