Repository micrometer-metrics/micrometer, pull requests merged in 2019-03, with the labels that each got.

#1249 Polish MeterRegistry
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1179 Forbid instance creation for stateless utility classes
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/DoubleFormat.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/JsonUtils.java
Labels: polish

#1257 Make auto-configuration of RestTemplate metrics back off with no builder bean
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/web/client/RestTemplateMetricsAutoConfiguration.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/web/client/RestTemplateMetricsAutoConfigurationIntegrationTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/web/client/RestTemplateMetricsAutoConfigurationTest.java
Labels: boot2-change

#1258 Fix conditional on beans for HibernateMetricsAutoConfiguration
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/orm/jpa/HibernateMetricsAutoConfiguration.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/orm/jpa/HibernateMetricsAutoConfigurationTest.java
Labels: bug

#1260 Start line sink only when enabled in StatsD meter registry
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
Labels: bug, registry: statsd

#1263 Use noop processor when publishing is disabled in StatsD meter registry
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
Labels: bug, registry: statsd

#1259 Revert gh-1119
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/tomcat/TomcatMetricsBinder.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/web/servlet/TomcatMetricsBinderTest.java
Labels: boot2-change, polish

#1264 Get Timed annotation from proxy target when failed
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/TimedAspectTest.java
Labels: bug

#1266 Add a test for multiple registrations of the same name of gauge
  micrometer-core/src/test/java/io/micrometer/core/instrument/MeterRegistryTest.java
Labels: polish

#1272 Polish Elasticsearch ingest pipeline and index separator support
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticMeterRegistryTest.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/elastic/ElasticProperties.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/elastic/ElasticPropertiesConfigAdapter.java
Labels: polish, registry: elastic

#1275 Add continuation indent size to .editorconfig
  .editorconfig
Labels: type: task

#1273 Add Javadoc on multiple meter registrations having the same ID
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1277 Use MissingRequiredConfigurationException consistently for 1.0.x
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
Labels: enhancement

#1284 Handle missing exceptions in WebMvcMetricsFilter
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/servlet/WebMvcMetricsFilter.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/web/servlet/WebMvcMetricsFilterTest.java
Labels: boot2-change, bug

#1270 Consistently throw MissingRequiredConfigurationException from MeterRegistry implementations
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: type: task

#1294 Use the latest DTD for Checkstyle configuration
  config/checkstyle/checkstyle.xml
Labels: type: task

#1305 Upgrade to Gradle Wrapper 5.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type: task

#1307 Upgrade to Checkstyle 8.18
  build.gradle
Labels: type: task

#1310 Use injected clock for auto-configured Stackdriver meter registry
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/stackdriver/StackdriverMetricsExportAutoConfiguration.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/prometheus/PrometheusMetricsExportAutoConfigurationTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/stackdriver/StackdriverMetricsExportAutoConfigurationTests.java
Labels: bug

#1312 Add Infinity Buckets to the StatsD MeterRegistry for Meters with an SLA
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/HistogramGauges.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/distribution/HistogramGaugesTest.java
Labels: enhancement, registry: statsd

#1245 Run release script and maven central sync from CI for release tags
  .circleci/config.yml
Labels: type: task

#1256 Polish zero-count bucket trimming logic in StackdriverMeterRegistry
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: polish, registry: stackdriver

#1333 Add Javadoc since tags for Wavefront classes
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontNamingConvention.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/wavefront/WavefrontMetricsExportAutoConfiguration.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/wavefront/WavefrontProperties.java
Labels: polish, registry: wavefront

#1339 Polish ImmutableTag
  micrometer-core/src/main/java/io/micrometer/core/instrument/ImmutableTag.java
Labels: polish

#1318 URL Cleanup
  README.md
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/DoubleFormat.java
Labels: polish

#1341 Polish Tags
  micrometer-core/src/main/java/io/micrometer/core/instrument/Tags.java
Labels: polish
