Repository micrometer-metrics/micrometer, pull requests merged in 2019-11, with the labels that each got.

#1683 Upgrade to Gradle 5.6.4
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1686 Use random port for TomcatMetricsTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: type: task

#1708 Javadoc fixes
  micrometer-core/src/main/java/io/micrometer/core/instrument/LongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1709 Polish Javadoc for LongTaskTimer
  micrometer-core/src/main/java/io/micrometer/core/instrument/LongTaskTimer.java
Labels: polish

#1718 Fix brittle assertion for tomcat.global.sent
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: polish

#1717 Remove unnecessary boxing
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogConfig.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaConfig.java
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteConfig.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxConfig.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusConfig.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java
Labels: polish

#1723 Upgrade to Shadow Plugin 5.2.0
  implementations/micrometer-registry-statsd/build.gradle
  micrometer-core/build.gradle
Labels: type: task

#1721 Fix warnings in TomcatMetricsTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: polish

#1661 Log custom meter names having leading numeric characters for Dynatrace
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceNamingConvention.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/WarnThenDebugLogger.java
Labels: enhancement, registry: dynatrace
