Repository micrometer-metrics/micrometer, pull requests merged in 2019-10, with the labels that each got.

#1223 Add instrumentation for pools of HttpComponents HttpClient
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinder.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinderTest.java
Labels: enhancement

#1621 Polish
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedExecutor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedExecutorService.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedScheduledExecutorService.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
Labels: polish

#1625 Fix Javadoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1624 Restore logging in JvmGcMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
Labels: type: task

#1630 Make DynatraceMeterRegistryTest.writeCustomMetrics() pass consistently
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
Labels: polish

#1631 Fix description for httpcomponents.httpclient.pool.total.connections
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinder.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinderTest.java
Labels: polish

#1623 Use internal logging for LoggingMeterRegistry
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
Labels: type: task

#1644 Polish New Relic contribution
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish

#1652 Remove org.ow2.asm:asm
  build.gradle
Labels: type: task

#1638 Add Javadoc indicating that SLA units are nanoseconds when they are meant for a Timer
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: polish

#1650 Upgrade to Gradle 5.6.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1657 Use HTTPS for links in license headers
  implementations/micrometer-registry-datadog/src/test/java/io/micrometer/datadog/DatadogConfigTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/AbstractInternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/FormattingTuple.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLogLevel.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/InternalLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/LocationAwareSlf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/MessageFormatter.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/package-info.java
Labels: polish

#1632 Add log for gauge's value function application failure
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java
Labels: enhancement

#1668 Remove the deprecated HumioConfig.repository()
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioConfig.java
Labels: registry: humio, type: task

#1672 Revert "Fixate OkHttp 3.x"
  micrometer-core/build.gradle
Labels: type: task

#1675 Use HTTPS for links in license headers on 1.3.x
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinder.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherThreadPool.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedCallable.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedRunnable.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedScheduledExecutorService.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinderTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherThreadPoolTest.java
Labels: type: task

#1669 Add log for gauge's value function application failure for DefaultGauge
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/WarnThenDebugLogger.java
Labels: enhancement

#1635 New Relic Micrometer Spring Legacy Updates
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicProperties.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicMetricsExportAutoConfigurationTests.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicPropertiesTests.java
Labels: registry: new relic, spring-boot change
