Repository micrometer-metrics/micrometer, pull requests merged in 2019-02, with the labels that each got.

#1201 Respect mode for FunctionTimer/FunctionCounter in SimpleMeterRegistry
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/simple/SimpleMeterRegistryTest.java
Labels: bug

#1198 Polish New Relic Insights support
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicNamingConvention.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicMetricsExportAutoConfiguration.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicProperties.java
Labels: polish

#1202 Align access modifiers for properties config adapters
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/newrelic/NewRelicPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/signalfx/SignalFxPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/simple/SimplePropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/statsd/StatsdPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/wavefront/WavefrontPropertiesConfigAdapter.java
Labels: polish

#1199 Polish OkHttpSender
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/OkHttpSender.java
Labels: polish

#1203 Align tests' class names with their test target class names
  micrometer-test/src/test/java/io/micrometer/core/ipc/http/HttpUrlConnectionSenderTest.java
  micrometer-test/src/test/java/io/micrometer/core/ipc/http/ReactorNettySenderTest.java
Labels: polish

#1204 Align access modifiers for properties config adapters for 1.1.x
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/kairos/KairosPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/logging/LoggingRegistryPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/stackdriver/StackdriverPropertiesConfigAdapter.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/appoptics/AppOpticsPropertiesConfigAdapterTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/kairos/KairosPropertiesConfigAdapterTest.java
Labels: polish

#1205 Polish "Add tests for ipc http package"
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/HttpUrlConnectionSender.java
  micrometer-core/src/test/java/io/micrometer/core/ipc/http/HttpUrlConnectionSenderTest.java
  micrometer-core/src/test/java/io/micrometer/core/ipc/http/OkHttpSenderTest.java
Labels: polish

#1210 Use JUnit platform consistently
  build.gradle
  implementations/micrometer-registry-atlas/build.gradle
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-datadog/build.gradle
  implementations/micrometer-registry-ganglia/build.gradle
  implementations/micrometer-registry-graphite/build.gradle
  implementations/micrometer-registry-influx/build.gradle
  implementations/micrometer-registry-jmx/build.gradle
  implementations/micrometer-registry-new-relic/build.gradle
  implementations/micrometer-registry-prometheus/build.gradle
  implementations/micrometer-registry-signalfx/build.gradle
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-wavefront/build.gradle
  micrometer-core/build.gradle
  micrometer-jersey2/build.gradle
  micrometer-jersey2/gradle/dependency-locks/testRuntimeClasspath.lockfile
  micrometer-spring-legacy/build.gradle
  micrometer-spring-legacy/gradle/dependency-locks/testRuntimeClasspath.lockfile
  micrometer-test/build.gradle
Labels: type: task

#1209 Fix broken tests
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/MetricsAutoConfigurationIntegrationTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/MetricsAutoConfigurationTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/export/humio/HumioMetricsExportAutoConfigurationTest.java
Labels: polish

#1166 #878: Fix kafka consumer fetch manager metrics to be reported per topic and…
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetricsTest.java
Labels: bug

#1219 Upgrade to Gradle Wrapper 5.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1220 Apply JMH Gradle plugin
  benchmarks/benchmarks-core/build.gradle
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/compare/CompareCountersWithOtherLibraries.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/compare/CompareHistogramsWithOtherLibraries.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/CounterBenchmark.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/MeterRegistrationBenchmark.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/TagsBenchmark.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/TimerBenchmark.java
  build.gradle
Labels: type: task

#1221 Respect time unit parameter in FunctionTimer.totalTime()
  micrometer-core/src/main/java/io/micrometer/core/instrument/FunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepFunctionTimer.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/cumulative/CumulativeFunctionTimerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepFunctionTimerTest.java
Labels: bug

#1225 Handle null MemoryUsage in JvmMemoryMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java
Labels: bug

#1216 Datadog: log when applicationKey is not configured
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java
Labels: enhancement

#1222 Use nanoseconds for Dropwizard timer snapshot mean
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimer.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimerTest.java
Labels: bug

#1233 Remove inaccurate statement from MeterRegistry#gauge JavaDoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1241 Fix a Javadoc warning for Timed.value()
  micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java
Labels: polish

#1240 Avoid using raw types for MultiGauge if possible
  micrometer-core/src/main/java/io/micrometer/core/instrument/MultiGauge.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/StrongReferenceGaugeFunction.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MultiGaugeTest.java
Labels: enhancement

#1237 Prevent publishing metrics to AppOptics when having no metrics
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
Labels: bug

#1246 Clean up compile warnings
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdGaugeTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/cumulative/CumulativeFunctionTimerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepFunctionTimerTest.java
Labels: polish

#1248 Polish Javadoc for Timer.wrap(Supplier)
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
Labels: polish
