Repository micrometer-metrics/micrometer, pull requests merged in 2019-07, with the labels that each got.

#1482 Upgrade to Gradle Wrapper 5.5
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type: task

#1485 Manage mockito-core in micrometer-test module
  implementations/micrometer-registry-appoptics/build.gradle
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-cloudwatch2/build.gradle
  implementations/micrometer-registry-statsd/build.gradle
  micrometer-test/build.gradle
Labels: type: task

#1486 Use consistent value for count in CloudWatch meter registry
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
Labels: polish, registry: cloudwatch

#1488 Use same time per publish in AppOptics meter registry
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
Labels: polish, registry: appoptics

#1490 Polish @Counted contribution
  micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java
  micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java
  micrometer-core/src/test/java/io/micrometer/core/aop/CountedAspectTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/CountedAspectTest.java
Labels: polish

#1491 Polish Dynatrace device group name contribution
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
Labels: polish, registry: dynatrace

#1496 Polish MongoDB client meter binder contribution
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/AbstractMongoDbTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListenerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListenerTest.java
Labels: polish

#1497 Fix NamingConvention.upperCamelCase.tagKey()
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/NamingConventionTest.java
Labels: bug

#1503 Remove nebula.optional-base plugin from CloudWatch modules
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-cloudwatch2/build.gradle
Labels: type: task

#1498 Improve Graphite name sanitization
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteHierarchicalNameMapper.java
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteNamingConvention.java
  implementations/micrometer-registry-graphite/src/test/java/io/micrometer/graphite/GraphiteHierarchicalNameMapperTest.java
  implementations/micrometer-registry-graphite/src/test/java/io/micrometer/graphite/GraphiteNamingConventionTest.java
Labels: registry: graphite

#1501 Add Javadoc since to default constructor in TimedAspect
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
Labels: polish

#1504 Polish CloudWatch modules
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/MetricDatumPartition.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/MetricDatumPartition.java
  implementations/micrometer-registry-cloudwatch2/src/test/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistryTest.java
Labels: polish, registry: cloudwatch

#1508 Fix typo
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/BufferingFlux.java
Labels: polish

#1506 Fix BufferingFluxTest.bufferMessagesCanBeAppended()
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/internal/BufferingFluxTest.java
Labels: type: task

#1514 Upgrade to Gradle Wrapper 5.5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1515 Fix method tag in TimedAspectTest.timeMethodFailureWithLongTaskTimer()
  micrometer-core/src/test/java/io/micrometer/core/aop/TimedAspectTest.java
Labels: type: task

#1516 Add Javadoc since tag to HttpUrlConnectionSender constructor
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/HttpUrlConnectionSender.java
Labels: polish

#1517 Add missing @Nullable for CallState constructor parameter
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
Labels: type: task

#1518 Polish MicrometerHttpRequestExecutor
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: polish

#1519 Make ElasticMeterRegistry inheritable
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
Labels: bug, registry: elastic

#1520 Add Javadoc since tag for LoggingMeterRegistry.Builder.meterIdPrinter()
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
Labels: type: task

#1528 Polish TimedExecutorService
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/TimedExecutorService.java
Labels: polish

#1533 Update javadocs for @Timed annotation
  micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java
Labels: polish
