Repository micrometer-metrics/micrometer, pull requests merged in 2019-01, with the labels that each got.

#1112 Align junit5 conventions and minor cleanup
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/db/PostgreSQLDatabaseMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/IOUtilsTest.java
  micrometer-core/src/test/java/io/micrometer/core/ipc/http/RequestTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/CompositeMeterRegistryConfigurationDefaultSimpleRegistryTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/CompositeMeterRegistryConfigurationExistingPrimaryRegistryTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/CompositeMeterRegistryConfigurationNoRegistryTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/CompositeMeterRegistryConfigurationSingleRegistryTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/MeterRegistryCustomizerTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/PropertiesMeterFilterIntegrationTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/integration/SpringIntegrationMetricsTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/jdbc/DataSourcePoolMetricsHikariTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/jdbc/DataSourcePoolMetricsTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/scheduling/ScheduledMethodMetricsTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/security/SpringSecurityTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/web/servlet/WebMvcMetricsFilterAutoTimedTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/web/servlet/WebMvcMetricsFilterCustomExceptionHandlerTest.java
Labels: polish

#1144 Polish Elasticsearch support
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticNamingConvention.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticMeterRegistryTest.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/elastic/ElasticMetricsExportAutoConfiguration.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/elastic/ElasticProperties.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/elastic/ElasticPropertiesConfigAdapter.java
Labels: polish

#1157 Avoid creating meter binders before registry has been customized
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MeterRegistryConfigurer.java
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MeterRegistryPostProcessor.java
Labels: bug

#1178 Avoid invoking String.getBytes() on payload if possible in Dynatrace
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
Labels: polish

#1182 Move TestController to test package
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/web/TestController.java
Labels: polish

#1191 Polish "Add tests for io.micrometer.core.instrument.noop package"
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopCounterTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopDistributionSummaryTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopFunctionCounterTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopFunctionTimerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopGaugeTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopTimeGaugeTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/noop/NoopTimerTest.java
Labels: polish

#1188 Add Javadoc for RestTemplateExchangeTags.outcome()
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/client/RestTemplateExchangeTags.java
Labels: polish

#1189 Add executor.queue.remaining for ThreadPoolExecutor
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
Labels: enhancement

#1158 "records-lead" in KafkaConsumerMetrics should not be a TimeGauge
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java
Labels: bug

#1195 Relax copyright year in license header
  build.gradle
  gradle/licenseHeader.txt
Labels: polish

#1193 [Issue#1192] Strip invalid characters from events for NR Naming convention.
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicNamingConvention.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicNamingConventionTest.java
Labels: bug
