Repository micrometer-metrics/micrometer, pull requests merged in 2020-05, with the labels that each got.

#2053 Polish ExecutorServiceMetrics changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
Labels: polish

#2043 Fix version in DistributionStatisticConfig.getSlaBoundaries() Javadoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: doc-update, polish

#2044 Fix tag mismatch in Jetty SSL handshake metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetricsTest.java
Labels: bug

#2062 Fix tag mismatch due to target tags in OkHttp metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java
Labels: bug

#2065 Fix tag mismatch due to request tags in OkHttp metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java
Labels: bug

#2073 Ensure clean-up in StatsdMeterRegistryPublishTest
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
Labels: polish

#2074 Remove unused DelegatingDropwizardLongGauge
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DelegatingDropwizardLongGauge.java
Labels: type: task

#2075 Fix ClassCastException in OpenTSDBMeterRegistry.writeLongTaskTimer()
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBLongTaskTimer.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBMeterRegistry.java
  implementations/micrometer-registry-opentsdb/src/test/java/io/micrometer/opentsdb/OpenTSDBMeterRegistryTest.java
Labels: bug, registry: opentsdb

#2077 Use strong reference for NewRelicMeterRegistryTest.publishWithApiClientProvider()
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: type: task

#2078 Use consistent value for active tasks in LongTaskTimer.mean()
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/LongTaskTimer.java
Labels: bug

#2079 Ensure clean-up in StatsdMeterRegistryTest
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
Labels: type: task

#1641 Polish TimeWindowMax
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowMax.java
Labels: polish

#2102 Fix deadlock in DatadogStatsdLineBuilder
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java
Labels: bug

#2101 Update naming convention consistently in StatsdLineBuilders
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/EtsyStatsdLineBuilder.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/SysdigStatsdLineBuilder.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/TelegrafStatsdLineBuilder.java
Labels: bug, enhancement

#2084 Autocloseable timer builder
  micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimerBuilder.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpClientInterceptor.java
  micrometer-test/src/main/java/io/micrometer/core/tck/TimerTest.java
Labels: enhancement

#2098 Fix Javadoc errors
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java
Labels: type: task

#2107 Polish build scripts for Spring Boot samples
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-spring-integration/build.gradle
Labels: build, polish

#2099 Retry failing assertion in TomcatMetricsTest
  micrometer-core/build.gradle
  micrometer-core/gradle/dependency-locks/testCompile.lockfile
  micrometer-core/gradle/dependency-locks/testCompileClasspath.lockfile
  micrometer-core/gradle/dependency-locks/testRuntime.lockfile
  micrometer-core/gradle/dependency-locks/testRuntimeClasspath.lockfile
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: type: task

#2106 Relax assertion for tomcat.threads.busy in TomcatMetricsTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: type: task

#2083 Prevent Graphite reporter from modifying user tags
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteMeterRegistry.java
  implementations/micrometer-registry-graphite/src/test/java/io/micrometer/graphite/GraphiteMeterRegistryTest.java
Labels: registry: graphite

#2110 Restore meter name suffixes for LongTaskTimer in PrometheusMeterRegistry
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
Labels: bug

#2111 Register NotificationListener unconditionally in CommonsObjectPool2Metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/CommonsObjectPool2Metrics.java
Labels: polish

#2115 Polish timer builder changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimerBuilder.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
  micrometer-test/src/main/java/io/micrometer/core/tck/TimerTest.java
Labels: polish
