Repository micrometer-metrics/micrometer, pull requests merged in 2020-04, with the labels that each got.

#1955 Deprecate PushRegistryConfig.numThreads()
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java
Labels: release notes, type: task

#1959 Polish histogram bucket type changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/DistributionSummary.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/MeterFilter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/CountAtBucket.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogramTest.java
Labels: polish

#1960 Polish JvmHeapPressureMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmHeapPressureMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowSum.java
Labels: polish

#1901 Use WavefrontSender interface in WavefrontMeterRegistry
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMetricLineData.java
  implementations/micrometer-registry-wavefront/src/test/java/io/micrometer/wavefront/WavefrontMeterRegistryTest.java
Labels: enhancement, registry: wavefront, release notes

#1963 Add Javadoc since to classes in io.micrometer.core.instrument.binder.http
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/DefaultHttpServletRequestTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpRequestTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpServletRequestTagsProvider.java
Labels: polish

#1966 Polish
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
Labels: polish

#1969 Polish OpenTSDB and VictoriaMetrics histogram changes
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBConfig.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBDistributionSummary.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBFlavor.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBMeterRegistry.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBNamingConvention.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBTimer.java
  implementations/micrometer-registry-opentsdb/src/test/java/io/micrometer/opentsdb/OpenTSDBMeterRegistryCompatibilityTest.java
  implementations/micrometer-registry-opentsdb/src/test/java/io/micrometer/opentsdb/OpenTSDBMeterRegistryTest.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/HistogramFlavor.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusConfig.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusDistributionSummary.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryVictoriaMetricsHistogram.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/distribution/FixedBoundaryVictoriaMetricsHistogramTest.java
Labels: polish

#1970 Fix MeterRegistry.gauge @return javadoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: polish

#1971 Polish HibernateQueryMetrics changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateQueryMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateQueryMetricsTest.java
Labels: polish

#1972 Fix percentile values for DistributionSummary in OpenTSDBMeterRegistry
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBMeterRegistry.java
Labels: bug, registry: opentsdb

#1976 Workaround WFLY-13345
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/OnCompletionAsyncListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/TimedHandler.java
Labels: bug

#1979 Check Wavefront mandatory attributes only if necessary
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/test/java/io/micrometer/wavefront/WavefrontMeterRegistryTest.java
Labels: registry: wavefront

#1980 Configure PushRegistry#batchSize for Wavefront
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/test/java/io/micrometer/wavefront/WavefrontMeterRegistryTest.java
Labels: enhancement, registry: wavefront

#1984 Polish Wavefront changes
  implementations/micrometer-registry-wavefront/build.gradle
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/test/java/io/micrometer/wavefront/WavefrontMeterRegistryTest.java
Labels: polish, registry: wavefront

#1983 Add jOOQ minimum version to MetricsDSLContext's Javadoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
Labels: polish

#1982 Use latest.release for jOOQ
  dependencies.gradle
Labels: type: task

#1988 Polish Kafka metrics changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java
Labels: polish

#1986 Relax assertion for jetty.threads.busy in test
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetricsTest.java
Labels: type: task

#1987 Suppress warnings for PushRegistryConfig.numThreads()
  micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/properties/StepRegistryPropertiesConfigAdapter.java
Labels: polish, type: task

#2000 Add tests for JvmGcMetrics
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetricsTest.java
Labels: type: task

#2009 Completable future support for @Counted
  micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java
  micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java
  micrometer-core/src/test/java/io/micrometer/core/aop/CountedAspectTest.java
Labels: enhancement

#2007 Update default value logic for graphite tags
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteConfig.java
Labels: enhancement, registry: graphite, release notes

#2016 Polish Javadoc for SLO changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: polish

#2004 Add get*ValueAsDouble and getServiceLevelObjectiveBoundaries methods …
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeDistributionSummary.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/PercentileHistogramBuckets.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MeterFilterTest.java
  micrometer-spring-legacy/src/test/java/io/micrometer/spring/autoconfigure/PropertiesMeterFilterTest.java
Labels: type: task

#2003 Update JavaDocs for deprecated get*ExpectedValue methods
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: type: task

#1975 Add Jetty handshake metrics binding
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetricsTest.java
Labels: enhancement

#2022 Polish LongTaskTimer changes
  implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/AtlasMeterRegistry.java
  implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/SpectatorLongTaskTimer.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusLongTaskTimer.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/LongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/HistogramGauges.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/noop/NoopLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
Labels: polish

#2025 Do not remap id in remove method
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MeterRegistryTest.java
Labels: bug

#2026 Polish @Timed changes
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
  micrometer-core/src/test/java/io/micrometer/core/aop/TimedAspectTest.java
Labels: polish

#2027 Polish Kafka metrics changes for multiple clients
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaMetricsTest.java
Labels: polish

#2030 Polish validation changes for meter registry configuration
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchConfig.java
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchConfig.java
  implementations/micrometer-registry-cloudwatch2/src/test/java/io/micrometer/cloudwatch2/CloudWatchConfigTest.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaConfig.java
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteConfig.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsAgentClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsApiClientProvider.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicConfigTest.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdConfig.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdConfigTest.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/MeterRegistryConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/MissingRequiredConfigurationException.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/DurationValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/InvalidReason.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/PropertyValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/Validated.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/ValidationException.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepRegistryConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/TimeUtils.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/push/PushRegistryConfigTest.java
Labels: polish

#2032 Only set Azure instrumentation key if not already set
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorConfig.java
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
  implementations/micrometer-registry-azure-monitor/src/test/java/io/micrometer/azuremonitor/AzureMonitorConfigTest.java
  implementations/micrometer-registry-azure-monitor/src/test/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistryTest.java
Labels: bug

#2034 Fix Javadoc warnings
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: polish

#2035 Fix Javadoc warnings
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPool.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyClientTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/MeterRegistryConfigValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/Validated.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultLongTaskTimer.java
Labels: polish

#2037 Polish JerseyTags
  micrometer-jersey2/src/main/java/io/micrometer/jersey2/server/JerseyTags.java
Labels: polish

#2036 Polish JettyClientMetrics changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyClientMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyClientTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/OnlyOnceLoggingDenyMeterFilter.java
Labels: polish

#1702 Aligning http clients tags between httpclient and okhttp
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java
Labels: enhancement

#2041 Additional ThreadPoolExecutor metrics for pool configuration
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
Labels: enhancement

#2042 Remove spring-test dependency
  dependencies.gradle
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/JCacheMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/EhCache2MetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/JCacheMetricsTest.java
Labels: type: task
