Repository micrometer-metrics/micrometer, pull requests merged in 2020-06, with the labels that each got.

#2128 Reduce flakiness in NewRelicMeterRegistryTest
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish

#2120 Prevent StringIndexOutOfBoundsException in Datadog statsD on empty tag value
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilderTest.java
Labels: bug, registry: statsd

#2134 Upgrade to Gradle Wrapper 6.5
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#2133 Fix Javadoc warnings
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultLongTaskTimer.java
Labels: polish

#2132 Reduce flakiness in NewRelicMeterRegistryTest
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: type: task

#2135 Reduce flakiness in NewRelicMeterRegistryTest
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish
