Repository micrometer-metrics/micrometer, pull requests merged in 2020-07, with the labels that each got.

#2172 Upgrade to Gradle Wrapper 6.5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#2173 Honor configured step duration when building Wavefront senders
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
Labels: bug, registry: wavefront

#2189 Replace deprecated MockitoAnnotations.initMocks() usages
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/JCacheMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetricsTest.java
Labels: polish

#2210 Replace deprecated Testcontainers usages
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/AbstractElasticsearchMeterRegistryIntegrationTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java
Labels: type: task

#2211 Use a fixed version for Kafka Docker image
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java
Labels: type: task
