Repository micrometer-metrics/micrometer, pull requests merged in 2020-03, with the labels that each got.

#1857 Upgrade to Gradle Wrapper 6.2.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: type: task

#1869 Update default api endpoint
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogConfig.java
  implementations/micrometer-registry-datadog/src/test/java/io/micrometer/datadog/DatadogConfigTest.java
Labels: enhancement, registry: datadog

#1860 Add since to GraphiteHierarchicalNameMapper
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteHierarchicalNameMapper.java
Labels: polish

#1866 Run StatsdMeterRegistryPublishTest.receiveMetricsSuccessfully() only on Linux
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
Labels: type: task

#1873 Fix a Javadoc warning
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverNamingConvention.java
Labels: polish

#1865 Replace deprecated dependency configurations
  benchmarks/benchmarks-core/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-core/build.gradle
Labels: polish

#1876 Upgrade to Gradle Wrapper 6.2.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1877 Fix Javadoc error and warnings
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
Labels: polish

#1878 Apply NoHttpCheck
  build.gradle
  config/checkstyle/checkstyle.xml
  implementations/micrometer-registry-appoptics/gradle/dependency-locks/checkstyle.lockfile
  implementations/micrometer-registry-atlas/gradle/dependency-locks/checkstyle.lockfile
  implementations/micrometer-registry-cloudwatch/gradle/dependency-locks/checkstyle.lockfile
  implementations/micrometer-registry-datadog/gradle/dependency-locks/checkstyle.lockfile
  implementations/micrometer-registry-dynatrace/gradle/dependency-locks/checkstyle.lockfile
  implementations/micrometer-registry-elastic/gradle/dependency-locks/checkstyle.lockfile
  micrometer-core/gradle/dependency-locks/checkstyle.lockfile
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/JdkLoggerFactory.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/LocationAwareSlf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLogger.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/Slf4JLoggerFactory.java
  micrometer-spring-legacy/gradle/dependency-locks/checkstyle.lockfile
Labels: type: task

#1881 Use managed versions in micrometer-sample-core
  dependencies.gradle
  samples/micrometer-samples-core/build.gradle
Labels: polish

#1887 Polish Javadoc for StepCounter
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepCounter.java
Labels: polish

#1818 Add support for Stackdriver resource labels
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: enhancement, registry: stackdriver

#1888 Polish Datadog contribution
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMetricMetadata.java
  implementations/micrometer-registry-datadog/src/test/java/io/micrometer/datadog/DatadogMetricMetadataTest.java
Labels: polish, registry: datadog

#1890 Polish StepTimer max changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepValue.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepLongMaxTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepValueTest.java
Labels: polish

#1889 Add Javadoc since for StackdriverConfig.resourceLabels()
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
Labels: polish, registry: stackdriver

#1894 Apply SpringJUnit5Check Checkstyle module
  build.gradle
  config/checkstyle/checkstyle-suppressions.xml
  config/checkstyle/checkstyle.xml
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherThreadPoolTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/TimedHandlerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/simple/SimpleMeterRegistryTest.java
  micrometer-jersey2/build.gradle
Labels: type: task

#1896 Fix kafka same tags
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaMetricsTest.java
Labels: bug

#1897 Polish Elasticsearch index type changes
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticMeterRegistryTest.java
Labels: polish, registry: elastic

#1858 Performance enhancement for logback's isDebugEnabled (et al) calls.
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java
Labels: enhancement, performance

#1904 Polish Kafka meter binder changes
  dependencies.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaStreamsMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsAdminTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsConsumerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsProducerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/OldKafkaConsumerMetricsTest.java
  micrometer-test/build.gradle
Labels: polish

#1905 Use latest.release for com.github.charithe:kafka-junit
  dependencies.gradle
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/KafkaMetricsSample.java
Labels: type: task

#1908 Polish New Relic changes
  dependencies.gradle
  implementations/micrometer-registry-new-relic/build.gradle
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicAgentClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicHttpClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish, registry: new relic

#1328 Make the document type configurable when writing to ES index
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticMeterRegistryTest.java
Labels: registry: elastic

#1899 Remove @Support and @PlainSQL in MetricsDSLContext
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
Labels: polish

#1913 Rename tags provider classes to indicate Servlet dependency
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/DefaultHttpServletRequestTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpServletRequestTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/TimedHandler.java
Labels: polish

#1735 Move meter registry starting log to PushMeterRegistry
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaMeterRegistry.java
  implementations/micrometer-registry-humio/src/main/java/io/micrometer/humio/HumioMeterRegistry.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java
  implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java
Labels: polish

#1917 Newrelic java agent polish
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/ClientProviderType.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsAgentClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsApiClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish, registry: new relic

#1918 New Relic Registry Builder Polish
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish, registry: new relic

#1924 Note 1.4.x as non-LTS in README
  README.md
Labels: type: task

#1922 Polish New Relic changes
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/ClientProviderType.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
Labels: polish, registry: new relic

#1921 Polish MicrometerHttpClientInterceptor changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/DefaultUriMapper.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/HttpContextUtils.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpClientInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpClientInterceptorTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: polish

#1927 Use micrometer-core project dependency in micrometer-samples-boot2
  samples/micrometer-samples-boot2/build.gradle
Labels: type: task

#1932 Handle NaN for FunctionTimer in ElasticMeterRegistry
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticMeterRegistryTest.java
Labels: bug, registry: elastic

#1939 Upgrade to Gradle Wrapper 6.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#1940 Remove configuration for checkstyle task
  build.gradle
Labels: build

#1941 Add sum for FunctionTimer in CloudWatchMeterRegistry
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchMeterRegistryTest.java
Labels: bug, registry: cloudwatch

#1945 Polish CloudWatch changes
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchNamingConvention.java
  implementations/micrometer-registry-cloudwatch/src/test/java/io/micrometer/cloudwatch/CloudWatchNamingConventionTest.java
Labels: polish, registry: cloudwatch

#1946 Use retryWhen() in StatsdMeterRegistry
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
Labels: registry: statsd, type: task

#1949 Polish CloudWatch changes
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchConfig.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchNamingConvention.java
  implementations/micrometer-registry-cloudwatch2/src/test/java/io/micrometer/cloudwatch2/CloudWatchNamingConventionTest.java
Labels: polish, registry: cloudwatch

#1953 Drop zero-count infinity bucket in StackdriverMeterRegistry
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: registry: stackdriver
