Repository micrometer-metrics/micrometer, pull requests merged in 2020-02, with the labels that each got.

#1836 Time remaining selectFrom() methods for jOOQ
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
Labels: polish

#1837 Support running docker in tests on CircleCI build
  .circleci/config.yml
  build.gradle
Labels: type: task

#1434 Add integration tests for Elasticsearch meter registry
  implementations/micrometer-registry-elastic/build.gradle
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/AbstractElasticsearchMeterRegistryIntegrationTest.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch6IntegrationTest.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch7IntegrationTest.java
  micrometer-test/build.gradle
Labels: registry: elastic

#1849 Use Elasticsearch 7.6.0 Docker image for integration tests
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch7IntegrationTest.java
Labels: type: task
