Repository micrometer-metrics/micrometer, pull requests merged in 2020-10, with the labels that each got.

#2278 Upgrade machine executor image to ubuntu-1604:202007-01
  .circleci/config.yml
Labels: build, type: task

#2287 Add ch.qos.logback:logback-classic to micrometer-registry-elastic test scope
  implementations/micrometer-registry-elastic/build.gradle
Labels: registry: elastic, type: task

#2292 Use default constructor for atomic objects with default initial value
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/BufferingFlux.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdGaugeTest.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryVictoriaMetricsHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionCounter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/CumulativeHistogramLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/OnlyOnceLoggingDenyMeterFilter.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MeterFilterTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/TimeGaugeTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/composite/CompositeMeterRegistryTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepMeterRegistryTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/CounterTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/GaugeTest.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/CounterSample.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/FunctionCounterSample.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/FunctionTimerSample.java
Labels: type: task

#2289 Remove Testcontainers from micrometer-test
  implementations/micrometer-registry-elastic/build.gradle
  micrometer-test/build.gradle
Labels: type: task

#2296 Upgrade to Gradle Wrapper 6.7
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#2298 Use JMX domain from Manager by default in TomcatMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
Labels: bug

#2241 Refine Javadoc for CacheMeterBinder.putCount()
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java
Labels: type: task

#2169 Use implicit default values for volatile fields
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdCounter.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdDistributionSummary.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdTimer.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowMax.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowSum.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultLongTaskTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepFunctionTimer.java
Labels: performance, type: task

#2311 Spam less with KafkaMetrics and Prometheus
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
Labels: type: task

#2313 Polish
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
Labels: polish

#2248 Add tomcat connection metrics.
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
Labels: enhancement

#2288 Change default index name prefix to "micrometer-metrics"
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/AbstractElasticsearchMeterRegistryIntegrationTest.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch6IntegrationTest.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch7IntegrationTest.java
Labels: registry: elastic, release notes

#2199 Add counters for QueryPlanCacheHit and QueryPlanCacheMiss in HibernateMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateMetricsTest.java
Labels: enhancement
