Repository micrometer-metrics/micrometer, pull requests merged in 2020-01, with the labels that each got.

#1770 Add Javadoc since tag for Counted.extraTags
  micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java
Labels: polish

#1768 Make functionTimerUnits() pass in OpenJ9
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
Labels: type: task

#1767 Fix running condition for ProcessorMetricsTest.hotspotCpuMetrics()
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/ProcessorMetrics.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java
Labels: type: task

#1766 Add more base unit definitions
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ClassLoaderMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/Log4j2Metrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/FileDescriptorMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
Labels: type: task

#1772 Add BaseUnits.MILLISECONDS
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmCompilationMetrics.java
Labels: polish

#1716 Support metrics for Apache http components async client pools
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinder.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/PoolingHttpClientConnectionManagerMetricsBinderTest.java
Labels: enhancement, release notes

#1764 Add JOOQ SQL metrics
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/JooqExecuteListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/db/MetricsDSLContextTest.java
Labels: enhancement

#1774 Fix statistics disabled tests for HibernateMetrics
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateMetricsTest.java
Labels: type: task

#1776 Fix flaky tests in HibernateMetricsTest due to GC
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jpa/HibernateMetricsTest.java
Labels: type: task

#1788 Reduces code used to implement AbstractPartition and backfills tests
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/AbstractPartition.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/MathUtils.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/AbstractPartitionTest.java
Labels: type: task

#1790 Changes StringEscapeUtils to be based on ASL code
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java
Labels: type: task

#1798 Fix execution of ./gradlew :micrometer-benchmarks-core:jmh
  benchmarks/benchmarks-core/build.gradle
  build.gradle
Labels: type: task

#1803 Adds NOTICE file for copy/paste/modified code
  NOTICE
Labels: type: task

#1804 Add pcollections copyright and license to LICENSE file
  LICENSE
Labels: type: task

#1693 Polish
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
Labels: polish

#1801 Upgrade to Gradle 6.1
  benchmarks/benchmarks-core/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  micrometer-core/build.gradle
Labels: enhancement, type: task

#1682 Stackdriver - Ability to configure credentials
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/UserAgentHeaderProvider.java
Labels: enhancement, registry: stackdriver, spring-boot change

#1812 Use java-platform to configure platform instead of spring dependencies.
  build.gradle
  micrometer-bom/build.gradle
Labels: type: task

#1815 Use modern Gradle features for declaring classpath dependencies.
  build.gradle
  implementations/micrometer-registry-appoptics/build.gradle
  implementations/micrometer-registry-atlas/build.gradle
  implementations/micrometer-registry-azure-monitor/build.gradle
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-cloudwatch2/build.gradle
  implementations/micrometer-registry-datadog/build.gradle
  implementations/micrometer-registry-dynatrace/build.gradle
  implementations/micrometer-registry-elastic/build.gradle
  implementations/micrometer-registry-ganglia/build.gradle
  implementations/micrometer-registry-graphite/build.gradle
  implementations/micrometer-registry-humio/build.gradle
  implementations/micrometer-registry-influx/build.gradle
  implementations/micrometer-registry-jmx/build.gradle
  implementations/micrometer-registry-kairos/build.gradle
  implementations/micrometer-registry-new-relic/build.gradle
  implementations/micrometer-registry-prometheus/build.gradle
  implementations/micrometer-registry-signalfx/build.gradle
  implementations/micrometer-registry-stackdriver/build.gradle
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-wavefront/build.gradle
  micrometer-core/build.gradle
  micrometer-jersey2/build.gradle
  micrometer-test/build.gradle
Labels: type: task

#1816 Use latest.release for wiremock-junit5
  micrometer-core/build.gradle
Labels: type: task

#1724 Dont create stackdriver metrics if they already exists
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
Labels: enhancement, registry: stackdriver

#1817 Use predefined base units
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyConnectionMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/TimedHandler.java
Labels: type: task

#1782 Rewrite Statsd publishing implementation
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdCounter.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdDistributionSummary.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdFunctionCounter.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdFunctionTimer.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdGauge.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdLongTaskTimer.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMetrics.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdTimer.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/LogbackMetricsSuppressingFluxSink.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/LogbackMetricsSuppressingUnicastProcessor.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  implementations/micrometer-registry-statsd/src/test/resources/logback.xml
  micrometer-core/build.gradle
Labels: registry: statsd, release notes

#1819 Move dependency version declarations to one location using dependency…
  build.gradle
  dependencies.gradle
  implementations/micrometer-registry-appoptics/build.gradle
  implementations/micrometer-registry-atlas/build.gradle
  implementations/micrometer-registry-azure-monitor/build.gradle
  implementations/micrometer-registry-cloudwatch/build.gradle
  implementations/micrometer-registry-cloudwatch2/build.gradle
  implementations/micrometer-registry-datadog/build.gradle
  implementations/micrometer-registry-dynatrace/build.gradle
  implementations/micrometer-registry-elastic/build.gradle
  implementations/micrometer-registry-ganglia/build.gradle
  implementations/micrometer-registry-graphite/build.gradle
  implementations/micrometer-registry-humio/build.gradle
  implementations/micrometer-registry-influx/build.gradle
  implementations/micrometer-registry-jmx/build.gradle
  implementations/micrometer-registry-kairos/build.gradle
  implementations/micrometer-registry-new-relic/build.gradle
  implementations/micrometer-registry-prometheus/build.gradle
  implementations/micrometer-registry-signalfx/build.gradle
  implementations/micrometer-registry-stackdriver/build.gradle
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-wavefront/build.gradle
  micrometer-core/build.gradle
  micrometer-jersey2/build.gradle
  micrometer-test/build.gradle
Labels: type: task

#1822 Update NOTICE header and add PCollections to NOTICE file
  NOTICE
Labels: type: task

#1825 Upgrade to Gradle Wrapper 6.1.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task

#1826 Use latest.release for org.apache.httpcomponents
  dependencies.gradle
Labels: type: task

#1823 Polish JettyConnectionMetricsTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettyConnectionMetricsTest.java
Labels: polish

#1824 Add Gradle Wrapper Validation GitHub Action
  .github/workflows/gradle-wrapper-validation.yml
Labels: type: task

#1829 Polish Stackdriver contribution
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/UserAgentHeaderProvider.java
Labels: polish, registry: stackdriver
