Repository micrometer-metrics/micrometer, pull requests merged in 2020-11, with the labels that each got.

#2322 Fix javadocs error
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/DefaultUriMapper.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/JsonUtils.java
Labels: polish

#2324 Remove unused Search.exactNameMatch
  micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java
Labels: polish

#2327 Fix deadlock in SysdigStatsdLineBuilder
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/SysdigStatsdLineBuilder.java
Labels: bug, registry: statsd

#2328 Polish Javadoc for Search
  micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java
Labels: polish

#2344 Upgrade to test-retry-gradle-plugin 1.1.9
  build.gradle
Labels: type: task

#2348 Upgrade to Gradle Wrapper 6.7.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#2347 Polish JvmMemoryTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryTest.java
Labels: polish

#2346 Use latest.release for de.flapdoodle.embed.mongo
  dependencies.gradle
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/AbstractMongoDbTest.java
Labels: type: task

#2350 Add Javadoc since to Search.tagKeys(Collection<String>)
  micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java
Labels: polish

#2361 Drop support for Elasticsearch 6
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/ElasticsearchMeterRegistryElasticsearch6IntegrationTest.java
Labels: registry: elastic, release notes

#2364 Set index to false for metric values in ElasticMeterRegistry
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
Labels: enhancement, registry: elastic
