Repository micrometer-metrics/micrometer, pull requests merged in 2021-04, with the labels that each got.

#2554 Clarify internal naming in JvmGcMetrics implementation
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemory.java
Labels: type: task

#2551 Introduce a skip predicate to the TimedAspect and CountedAspect
  micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
  micrometer-core/src/test/java/io/micrometer/core/aop/CountedAspectTest.java
  micrometer-core/src/test/java/io/micrometer/core/aop/TimedAspectTest.java
Labels: enhancement

#2556 Polish aspect changes
  micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
Labels: polish

#2560 Refactor JvmGcMetrics with less specialized logic for non-gen collectors
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmHeapPressureMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemory.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryTest.java
Labels: type: task

#2562 Support multiple long lived heap memory pools
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmHeapPressureMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemory.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryTest.java
Labels: enhancement

#2564 Polish Datadog changes
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilderTest.java
Labels: polish, registry: statsd

#2567 Pin version for org.hsqldb:hsqldb to 2.5.+
  dependencies.gradle
Labels: build, type: task

#2571 Polish changes for GC metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmHeapPressureMetrics.java
Labels: polish

#2568 Move tasks for GC tests to micrometer-core
  build.gradle
  micrometer-core/build.gradle
Labels: build, type: task

#2573 Log meter polling failure in `StatsdMeterRegistry`
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
Labels: polish, type: task

#2579 Fixing branch name references in circleci config and .md files
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
Labels: type: task

#2583 Configure Gradle enterprise conventions
  settings.gradle
Labels: build, type: task

#1663 Apply Gradle build cache
  .gitignore
  gradle.properties
Labels: build, type: task

#1600 Apply Gradle parallel execution
  gradle.properties
Labels: build, type: task
