Repository micrometer-metrics/micrometer, pull requests merged in 2021-07, with the labels that each got.

#2685 Pin jOOQ to 3.14.+
  dependencies.gradle
Labels: build, type: task

#2688 Polish error log message in `DynatraceExporterV2`
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
Labels: type: task

#2689 Polish logging test support
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  micrometer-test/src/main/java/io/micrometer/core/util/internal/logging/MockLogger.java
  micrometer-test/src/main/java/io/micrometer/core/util/internal/logging/MockLoggerFactory.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/LogEventTest.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/MockLoggerFactoryTest.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/MockLoggerTest.java
Labels: polish

#2690 Fix Javadoc errors
  micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
Labels: type: task

#2691 Polish MongoDB collection name tag changes
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoCommandTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoCommandTagsProvider.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoCommandTagsProviderTest.java
Labels: polish

#2687 Replace okhttp3.internal.http.HttpMethod.requiresRequestBody()
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/OkHttpSender.java
Labels: type: task

#2658 Update Spring Boot example config for Dynatrace
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/DynatraceSampleV1.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/DynatraceSampleV2.java
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v1.yml
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v2.yml
Labels: registry: dynatrace, type: task

#2692 Rename OneAgentMetadataEnrichment to DynatraceMetadataEnrichment
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceConfigTest.java
Labels: registry: dynatrace, type: task

#2696 Suppress `IllegalImport` check for samples
  config/checkstyle/checkstyle-suppressions.xml
Labels: type: task

#2698 Update Dynatrace metric library usage
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
Labels: type: task

#2520 Use cimg/openjdk:16.0.1 for CircleCI
  .circleci/config.yml
  micrometer-core/gradle.lockfile
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
Labels: build, enhancement

#2603 Add connector name tag for `JettyConnectionMetrics` and `JettySslHandshakeMetricsBinder`
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyConnectionMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettySslHandshakeMetrics.java
Labels: enhancement, module: micrometer-core

#2713 Update Dynatrace samples for Spring Boot autoconfiguration
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v1.yml
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v2.yml
Labels: type: task

#2718 Add meter name to error message.
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
Labels: module: micrometer-core, type: task

#2724 Update samples to use Spring Boot 2.6.0-M1
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-spring-integration/build.gradle
  settings.gradle
Labels: type: task
