Repository micrometer-metrics/micrometer, pull requests merged in 2021-03, with the labels that each got.

#2477 Update machine-executor.image to ubuntu-2004:202101-01
  .circleci/config.yml
Labels: build, type: task

#2479 Update circle-jdk-executor.image to cimg/openjdk:15.0.1
  .circleci/config.yml
Labels: build, type: task

#2471 Fix JDK source and target of published artifacts.
  build.gradle
Labels: bug, build

#2500 Polish
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
Labels: polish

#2501 Remove PrometheusFilteredSample
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/PrometheusFilteredSample.java
Labels: polish

#2503 Enforce signing artifacts if circleci runs the deploy stage.
  build.gradle
Labels: build, type: task

#2502 Remove maven-central-sync job
  .circleci/config.yml
  scripts/sync-to-maven-central.sh
Labels: type: task

#2360 Adds pluggable tags provider to MongoMetricsCommandListener
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoMetricsCommandTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandTagsProvider.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListenerTest.java
Labels: enhancement

#2437 Add MongoMetricsConnectionPoolTagsProvider
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoMetricsConnectionPoolTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolTagsProvider.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListenerTest.java
Labels: enhancement

#2485 Fix duplicate +Inf bucket in Prometheus histograms
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
Labels: bug, registry: prometheus

#2518 Update samples to use Spring Boot 2.4.4
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-spring-integration/build.gradle
Labels: type: task

#2523 Polish "Migrating to mongo client 4.x"
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListenerTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListenerTest.java
Labels: polish

#2529 Polish changes from InfluxDB v2 support
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxApiVersion.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxConfig.java
  implementations/micrometer-registry-influx/src/test/java/io/micrometer/influx/InfluxMeterRegistryVersionsTest.java
Labels: polish, registry: influx

#2522 Upgrade to JMH Gradle plugin 0.6.2
  benchmarks/benchmarks-core/build.gradle
  benchmarks/benchmarks-core/gradle/dependency-locks/jmhAnnotationProcessor.lockfile
  benchmarks/benchmarks-core/gradle/dependency-locks/jmhCompileClasspath.lockfile
Labels: build, type: task

#2531 Exclude netty http modules
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-statsd/gradle/dependency-locks/compileClasspath.lockfile
  implementations/micrometer-registry-statsd/gradle/dependency-locks/default.lockfile
  implementations/micrometer-registry-statsd/gradle/dependency-locks/runtimeClasspath.lockfile
  implementations/micrometer-registry-statsd/gradle/dependency-locks/testCompileClasspath.lockfile
  implementations/micrometer-registry-statsd/gradle/dependency-locks/testRuntimeClasspath.lockfile
Labels: build, enhancement, registry: statsd

#2532 Apply Checkstyle WhitespaceAfterCheck module
  config/checkstyle/checkstyle.xml
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/DoubleFormat.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/push/PushMeterRegistryTest.java
Labels: type: task

#2535 Add @FunctionalInterface on HttpServletRequestTagsProvider
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpServletRequestTagsProvider.java
Labels: polish

#2536 Add Javadoc since tag to changes from tags providers for MongoDB metrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoMetricsCommandTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoMetricsConnectionPoolTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolTagsProvider.java
Labels: polish

#2537 PrometheusTimer publishes wrong unit of time for max/sum when percentile histograms are enabled
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusTimer.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheus/PrometheusMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/HistogramSnapshot.java
Labels: bug, registry: prometheus
