Repository micrometer-metrics/micrometer, pull requests merged in 2021-02, with the labels that each got.

#2428 Upgrade to Gradle Wrapper 6.8.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build, type: task

#2432 Polish CaffeineStatsCounter contribution
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineStatsCounter.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/CaffeineStatsCounterTest.java
Labels: enhancement

#2430 Suppress deprecation warnings from MetricsDSLContext
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java
Labels: enhancement

#2433 Polish gRPC integration contribution
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/AbstractMetricCollectingInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingClientCall.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingClientCallListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingClientInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingServerCall.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingServerCallListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingServerInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/package-info.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/GrpcMetricsSample.java
Labels: enhancement

#2434 Support Javadoc @apiNote, @implSpec and @implNote
  build.gradle
Labels: enhancement

#2435 Clean up Javadoc warnings and errors
  micrometer-core/src/main/java/io/micrometer/core/instrument/TimeGauge.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineCacheMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineStatsCounter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingClientInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/MetricCollectingServerInterceptor.java
Labels: enhancement

#2438 Fix FunctionCounter in SingleIndicator.Builder.count()
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
  implementations/micrometer-registry-health/src/test/java/io/micrometer/health/QueryTest.java
Labels: bug

#2436 Use latest.release for Hazelcast version
  dependencies.gradle
Labels: build, enhancement

#2443 Log ExecutorServiceMetrics.bindTo() failure
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java
Labels: enhancement

#2444 Apply ModifierOrder Checkstyle module
  config/checkstyle/checkstyle.xml
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetricsTest.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/KafkaMetricsSample.java
Labels: enhancement

#2445 Use NamedThreadFactory in KafkaMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
Labels: polish

#2449 Polish NamedThreadFactory
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/NamedThreadFactory.java
Labels: polish

#2451 Fix flakiness in Log4j2MetricsTest.asyncLogShouldNotBeDuplicated()
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/logging/Log4j2MetricsTest.java
Labels: type: task

#2441 Polish micrometer-registry-health module
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/HealthConfig.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/QueryUtils.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/objectives/JvmServiceLevelObjectives.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/objectives/OperatingSystemServiceLevelObjectives.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/package-info.java
  implementations/micrometer-registry-health/src/test/java/io/micrometer/health/HealthMeterRegistryTest.java
  implementations/micrometer-registry-health/src/test/java/io/micrometer/health/QueryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/ServiceLevelObjectiveConfiguration.java
Labels: polish, registry: health

#2456 Attribute nullability annotations to Spring Framework
  NOTICE
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNull.java
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNullApi.java
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNullFields.java
  micrometer-core/src/main/java/io/micrometer/core/lang/Nullable.java
Labels: type: task

#2466 Upgrade to Gradle Wrapper 6.8.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#2439 Fix MultipleIndicator.combine()
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
Labels: type: task

#2473 Fix Javadoc since for MultipleIndicator.combine()
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
Labels: polish

#2470 Polish
  NOTICE
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNull.java
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNullApi.java
  micrometer-core/src/main/java/io/micrometer/core/lang/NonNullFields.java
  micrometer-core/src/main/java/io/micrometer/core/lang/Nullable.java
Labels: polish

#2467 Replace jcenter() with mavenCentral()
  build.gradle
Labels: build, type: task

#2478 Support Caffeine 3
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineStatsCounter.java
Labels: type: task

#2472 Skip publishing Timer with zero count in AzureMonitorMeterRegistry
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
  implementations/micrometer-registry-azure-monitor/src/test/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistryTest.java
Labels: bug
