Repository micrometer-metrics/micrometer, pull requests merged in 2022-04, with the labels that each got.

#3109 Upgrade to Gradle Wrapper 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task, build

#3114 Change max heap size for Gradle daemon to 1 GB
  gradle.properties
Labels: type: task, build

#3117 Migrate away from antiquated language and use more inclusive terms.
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxNamingConvention.java
  implementations/micrometer-registry-signalfx/src/test/java/io/micrometer/signalfx/SignalFxNamingConventionTest.java
Labels: polish, registry: signalfx

#3093 Add resettable DistributionSummary and Timer for Dynatrace registry
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceDistributionSummary.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceSummary.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceSummarySnapshot.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceSummarySnapshotSupport.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceTimer.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceDistributionSummaryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceSummaryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceTimerTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
Labels: enhancement, registry: dynatrace

#3118 Polish SignalFx changes
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxConfig.java
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxMeterRegistry.java
  implementations/micrometer-registry-signalfx/src/test/java/io/micrometer/signalfx/SignalFxMeterRegistryTest.java
Labels: type: task, polish

#3122 1.10.x KeyValue & KeyValues
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/LogbackMetricsSuppressingFluxSink.java
  micrometer-commons/src/main/java/io/micrometer/common/ImmutableKeyValue.java
  micrometer-commons/src/main/java/io/micrometer/common/KeyValue.java
  micrometer-commons/src/main/java/io/micrometer/common/KeyValues.java
  micrometer-commons/src/main/java/io/micrometer/common/docs/TagKey.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/docs/DocumentedMeter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/MeterObservationHandler.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/TimerObservationHandler.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/AnyContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ConcreteContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/NullContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ObservationContextAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ObservationRegistryAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/TestObservationRegistry.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/TestObservationRegistryAssert.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationConfig.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationHandler.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationPredicate.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationTextPublisher.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/Kind.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpClientRequest.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpClientResponse.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpRequest.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpResponse.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpServerRequest.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/HttpServerResponse.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/Request.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/Response.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/context/HttpClientContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/context/HttpContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/context/HttpServerContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/DefaultHttpTagsProvider.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/HttpTags.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/HttpTagsProvider.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/Outcome.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTextPublisherTests.java
  micrometer-observation/src/test/java/io/micrometer/observation/TagsProviderTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryAssert.java
  micrometer-test/src/test/java/io/micrometer/core/tck/MeterRegistryAssertTests.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/ObservationHandlerSample.java
Labels: breaking-change

#3126 Use more generic KeyValue terminology in Observation and Common module
  micrometer-commons/src/main/java/io/micrometer/common/docs/KeyName.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/docs/DocumentedMeter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/TimerObservationHandler.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ObservationContextAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation-test/src/test/java/io/micrometer/core/tck/ObservationContextAssertTests.java
  micrometer-observation-test/src/test/java/io/micrometer/core/tck/TestObservationRegistryAssertTests.java
  micrometer-observation/build.gradle
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationConfig.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/context/HttpClientContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/context/HttpContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/DefaultHttpKeyValueProvider.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/HttpKeyValueProvider.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/HttpKeyValues.java
  micrometer-observation/src/test/java/io/micrometer/observation/KeyValuesProviderTest.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTextPublisherTests.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/ObservationHandlerSample.java
Labels: enhancement

#3132 Replace LinkedList
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepFunctionTimerTest.java
Labels: polish, registry: prometheus

#3131 Polish "Prometheus histogram exemplars" changes
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusDistributionSummary.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusHistogram.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogram.java
Labels: polish, registry: prometheus

#3136 Pin Jersey dependencies to 3.0.+ in its sample
  samples/micrometer-samples-jersey3/build.gradle
Labels: type: task

#3135 Fix failure messages in MeterRegistryAssert
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryAssert.java
  micrometer-test/src/test/java/io/micrometer/core/tck/MeterRegistryAssertTests.java
Labels: polish, module: micrometer-test

#3137 Polish ObservationTests
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTests.java
Labels: polish

#3134 Polish Dynatrace changes
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceDistributionSummary.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceSummary.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceTimer.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceDistributionSummaryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceSummaryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceTimerTest.java
Labels: polish, registry: dynatrace

#3142 Upgrade to Elasticsearch 8.1.3 and 7.17.3 for integration tests
  implementations/micrometer-registry-elastic/src/test/java/io/micrometer/elastic/AbstractElasticsearchMeterRegistryIntegrationTest.java
Labels: registry: elastic, dependency-upgrade

#3143 Upgrade to Gradle Enterprise plugin to 3.10
  settings.gradle
Labels: type: task, build

#3151 Polish
  micrometer-core/src/main/java/io/micrometer/core/instrument/docs/DocumentedMeter.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
Labels: polish

#3153 Polish OTLP registry changes
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpCounter.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpFunctionCounter.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogram.java
Labels: type: task, polish
