Repository micrometer-metrics/micrometer, pull requests merged in 2022-05, with the labels that each got.

#3148 Dynatrace registry: Truncate log output
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringUtils.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/StringUtilsTest.java
Labels: type: task, registry: dynatrace

#3155 Dynatrace registry: Print ignored config warning only when necessary
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceDistributionSummary.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/types/DynatraceTimer.java
Labels: type: task, registry: dynatrace

#3157 Polish Dynatrace changes
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
Labels: polish, registry: dynatrace

#3158 Added the getCurrentObservationScope method
  micrometer-observation-test/src/main/java/io/micrometer/core/tck/TestObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservationRegistry.java
Labels: enhancement, breaking-change

#3159 Config for OTLP Resource attributes
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpConfigTest.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpMeterRegistryTest.java
  implementations/micrometer-registry-otlp/src/test/resources/otlp-config.properties
Labels: enhancement, registry: otlp

#3178 Change package name of Observation TCK
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/AnyContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ConcreteContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/NullContextObservationHandlerCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistry.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistryAssert.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/AnyContextObservationHandlerCompatibilityKitTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ConcreteContextObservationHandlerCompatibilityKitTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/NullContextObservationHandlerCompatibilityKitTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationContextAssertTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationRegistryAssertTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationRegistryCompatibilityKitTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/TestObservationRegistryAssertTests.java
Labels: type: task

#3173 Fix generic parameters for composite observations
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationHandler.java
  micrometer-observation/src/test/java/io/micrometer/observation/AllMatchingCompositeObservationHandlerTests.java
  micrometer-observation/src/test/java/io/micrometer/observation/FirstMatchingCompositeObservationHandlerTests.java
Labels: bug

#3179 Use consistent casing for no-op
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservationRegistry.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationRegistryTest.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTests.java
Labels: type: task, breaking-change, module: micrometer-observation

#3182 Upgrade to Test Retry Gradle Plugin 1.4.0
  build.gradle
  buildscript-gradle.lockfile
Labels: dependency-upgrade

#3184 Add a note for MockLoggerFactory.injectLogger() about its limitation
  micrometer-test/src/main/java/io/micrometer/core/util/internal/logging/MockLoggerFactory.java
Labels: doc-update, type: task

#3183 Make DynatraceExporterV2.logger non-static
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
Labels: type: task

#3185 Reduce deprecation warnings where possible
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/package-info.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/StringUtilsTest.java
  micrometer-test/src/main/java/io/micrometer/core/util/internal/logging/MockLogger.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/LogEventTest.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/MockLoggerFactoryTest.java
  micrometer-test/src/test/java/io/micrometer/core/util/internal/logging/MockLoggerTest.java
Labels: type: task, polish

#3186 Polish naming and docs
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverConfig.java
  implementations/micrometer-registry-stackdriver/src/test/java/io/micrometer/stackdriver/MetricTypePrefixTest.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationTextPublisher.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservationRegistry.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTextPublisherTests.java
Labels: polish

#3188 Add missing `@` in formatter disabling comments
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/TimerBenchmark.java
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxMeterRegistry.java
  implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/AbstractMetricCollectingInterceptor.java
Labels: polish

#3194 TimedAspect `timedClass` missing `shouldSkip` predicate check
  micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java
  micrometer-core/src/test/java/io/micrometer/core/aop/TimedAspectTest.java
Labels: bug, module: micrometer-core

#3198 Polish Checkstyle suppression configuration
  config/checkstyle/checkstyle-suppressions.xml
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: type: task, polish

#3199 Upgrade to Spring Java Format 0.0.33
  build.gradle
  buildscript-gradle.lockfile
Labels: build, dependency-upgrade

#3200 Add missing package-info.java files
  config/checkstyle/checkstyle-suppressions.xml
  config/checkstyle/checkstyle.xml
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v1/package-info.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/package-info.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/objectives/package-info.java
  implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/util/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/annotation/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/aop/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/package-info.java
  micrometer-core/src/main/java/io/micrometer/core/lang/package-info.java
  micrometer-jersey2/src/main/java/io/micrometer/jersey2/server/package-info.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/binder/cache/package-info.java
  micrometer-test/src/main/java/io/micrometer/core/ipc/http/package-info.java
  micrometer-test/src/main/java/io/micrometer/core/package-info.java
  micrometer-test/src/main/java/io/micrometer/core/tck/package-info.java
  micrometer-test/src/main/java/io/micrometer/core/util/internal/logging/package-info.java
Labels: type: task

#3201 Make descriptions static where they are not
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java
Labels: enhancement, module: micrometer-core

#3202 Add `DynatraceConfig.DEFAULT`
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java
Labels: enhancement, registry: dynatrace
