Repository micrometer-metrics/micrometer, pull requests merged in 2022-06, with the labels that each got.

#3205 Update samples to use Spring Boot 2.7.0
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-spring-integration/build.gradle
Labels: dependency-upgrade

#3204 Polish `MetricsTurboFilter`
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java
Labels: polish

#3211 Polish
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowMax.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowSum.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/aop/CountedAspectTest.java
  micrometer-core/src/test/java/io/micrometer/core/aop/TimedAspectTest.java
Labels: polish

#3216 Avoid auto-boxing in `Measurement#getValue`
  micrometer-core/src/main/java/io/micrometer/core/instrument/Measurement.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeasurement.java
Labels: performance, module: micrometer-core

#3215 Add a LongTaskTimer for every Observation
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/TimerObservationHandler.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/ObservationHandlerSample.java
Labels: enhancement, module: micrometer-observation

#3235 Adds mechanism to change observation names depending
  micrometer-commons/src/main/java/io/micrometer/common/KeyValue.java
  micrometer-commons/src/main/java/io/micrometer/common/ValidatedKeyValue.java
  micrometer-commons/src/main/java/io/micrometer/common/docs/KeyName.java
  micrometer-commons/src/main/java/io/micrometer/common/docs/SemanticNameProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/LegacyOkHttpMetricsEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpDocumentedObservation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java
  micrometer-observation-conventions/README.adoc
  micrometer-observation-conventions/build.gradle
  micrometer-observation-conventions/semantic-convention/.gitignore
  micrometer-observation-conventions/semantic-convention/generate.sh
  micrometer-observation-conventions/semantic-convention/templates/SemanticAttributes.java.j2
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/ArrayBackedAttributes.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/ArrayBackedAttributesBuilder.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/AttributeKey.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/AttributeType.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/Attributes.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/AttributesBuilder.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/ImmutableKeyValuePairs.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/InternalAttributeKeyImpl.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/ReadOnlyArrayMap.java
  micrometer-observation-conventions/src/main/java/io/micrometer/conventions/common/Utils.java
  micrometer-observation-conventions/src/test/java/io/micrometer/conventions/common/AttributeKeyTests.java
  micrometer-observation-conventions/src/test/java/io/micrometer/conventions/common/AttributesTests.java
  micrometer-observation-conventions/src/test/java/io/micrometer/conventions/common/ImmutableKeyValuePairsTests.java
  micrometer-observation/build.gradle
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/OpenTelemetryHttpClientKeyValuesConvention.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/OpenTelemetryHttpKeyValuesConvention.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/http/tags/OpenTelemetryHttpServerKeyValuesConvention.java
  settings.gradle
Labels: enhancement

#3239 Upgrade to Gradle Enterprise Plugin 3.10.2
  settings.gradle
Labels: type: task, build

#3047 Add HighCardinalityTagsDetector
  micrometer-core/src/main/java/io/micrometer/core/instrument/HighCardinalityTagsDetector.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/HighCardinalityTagsDetectorTests.java
Labels: enhancement, module: micrometer-core

#3221 @Observed
  micrometer-observation/build.gradle
  micrometer-observation/src/main/java/io/micrometer/observation/annotation/Observed.java
  micrometer-observation/src/main/java/io/micrometer/observation/annotation/package-info.java
  micrometer-observation/src/main/java/io/micrometer/observation/aop/ObservedAspect.java
  micrometer-observation/src/main/java/io/micrometer/observation/aop/package-info.java
  micrometer-observation/src/test/java/io/micrometer/observation/aop/ObservedAspectTests.java
Labels: enhancement, module: micrometer-observation

#3248 Upgrade to Spring Java Format 0.0.34
  build.gradle
  buildscript-gradle.lockfile
  implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/AtlasUtils.java
  implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMetricMetadata.java
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteMeterRegistry.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBMeterRegistry.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBNamingConvention.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/MicrometerCollector.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusDistributionSummary.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusTimer.java
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxMeterRegistry.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/MetricsRequestEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/Log4j2Metrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/DurationValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/TimeUtils.java
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/HttpSender.java
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/OkHttpSender.java
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/ReactorNettySender.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/AbstractInternalLogger.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/JettyClientMetricsTest.java
  micrometer-jersey2/src/main/java/io/micrometer/jersey2/server/MetricsRequestEventListener.java
Labels: polish, dependency-upgrade

#3256 Added support for Kotlin co-routines
  dependencies.gradle
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/kotlin/KotlinObservationContextElement.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/kotlin/package-info.java
  micrometer-core/src/main/kotlin/io/micrometer/core/instrument/kotlin/asContextElement.kt
  micrometer-core/src/main/resources/META-INF/services/io.micrometer.context.ThreadLocalAccessor
  micrometer-core/src/test/kotlin/io/micrometer/core/instrument/kotlin/AsContextElementKtTests.kt
Labels: enhancement

#3255 New approach to naming conventions
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/DefaultOkHttpObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpDocumentedObservation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpKeyValuesProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/StandardizedOkHttpKeyValuesProvider.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationConvention.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationRegistryTest.java
Labels: enhancement
