Repository micrometer-metrics/micrometer, pull requests merged in 2022-09, with the labels that each got.

#3385 Replace SLA with SLO
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/InvalidConfigurationException.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogram.java
Labels: polish

#3386 Remove unnecessary overrides in Timer.Builder
  micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java
Labels: polish

#3383 Context allows modification of KeyValues
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/test/java/io/micrometer/observation/docs/DocumentedObservationTests.java
Labels: enhancement

#3391 Polish ProcessorMetricsTest
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java
Labels: polish

#3389 Backport JApicmp Gradle Plugin configuration
  build.gradle
  buildscript-gradle.lockfile
  gradle.properties
Labels: type: task, build

#3390 Enable Gradle's stable configuration cache feature flag
  settings.gradle
Labels: type: task, build

#3397 Upgrade to Spotless Gradle Plugin 6.10.0
  build.gradle
  buildscript-gradle.lockfile
Labels: build, dependency-upgrade

#3403 Polish
  implementations/micrometer-registry-signalfx/src/test/java/io/micrometer/signalfx/DeltaHistogramCountsTest.java
  implementations/micrometer-registry-signalfx/src/test/java/io/micrometer/signalfx/SignalFxMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/ObservationOrTimerCompatibleInstrumentation.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/observation/ObservationOrTimerCompatibleInstrumentationTest.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/SenderContext.java
Labels: polish

#3379 HTTP server instrumentation TCK
  config/checkstyle/checkstyle-suppressions.xml
  dependencies.gradle
  implementations/micrometer-registry-appoptics/gradle.lockfile
  implementations/micrometer-registry-atlas/gradle.lockfile
  implementations/micrometer-registry-azure-monitor/gradle.lockfile
  implementations/micrometer-registry-cloudwatch/gradle.lockfile
  implementations/micrometer-registry-cloudwatch2/gradle.lockfile
  implementations/micrometer-registry-datadog/gradle.lockfile
  implementations/micrometer-registry-dynatrace/gradle.lockfile
  implementations/micrometer-registry-elastic/gradle.lockfile
  implementations/micrometer-registry-ganglia/gradle.lockfile
  implementations/micrometer-registry-graphite/gradle.lockfile
  implementations/micrometer-registry-health/gradle.lockfile
  implementations/micrometer-registry-humio/gradle.lockfile
  implementations/micrometer-registry-influx/gradle.lockfile
  implementations/micrometer-registry-jmx/gradle.lockfile
  implementations/micrometer-registry-kairos/gradle.lockfile
  implementations/micrometer-registry-new-relic/gradle.lockfile
  implementations/micrometer-registry-opentsdb/gradle.lockfile
  implementations/micrometer-registry-prometheus/gradle.lockfile
  implementations/micrometer-registry-signalfx/gradle.lockfile
  implementations/micrometer-registry-stackdriver/gradle.lockfile
  implementations/micrometer-registry-wavefront/gradle.lockfile
  micrometer-jersey2/gradle.lockfile
  micrometer-test/build.gradle
  micrometer-test/gradle.lockfile
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JerseyServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JettyServerTimingInstrumentationVerificationTests.java
  samples/micrometer-samples-hazelcast3/gradle.lockfile
  samples/micrometer-samples-jersey3/gradle.lockfile
Labels: enhancement, module: micrometer-test

#3401 Add "createNotStarted" method that lazily creates context
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/test/java/io/micrometer/observation/docs/DocumentedObservationTests.java
Labels: enhancement, module: micrometer-observation

#3411 Automated java module checking
  build.gradle
Labels: enhancement

#3409 Override default spliterator method in Tags and KeyValues
  micrometer-commons/src/main/java/io/micrometer/common/KeyValues.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Tags.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/TagsTest.java
Labels: enhancement

#3410 Tck with observations
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/DefaultJerseyObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyDocumentedObservation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyKeyValues.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/ObservationApplicationEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/ObservationRequestEventListener.java
  micrometer-test/build.gradle
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/InstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/ApacheHttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JerseyServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JettyClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JettyServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/OkHttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java11/io/micrometer/core/instrument/JdkHttpClientTimingInstrumentationVerificationTests.java
Labels: enhancement, breaking-change

#3419 ReceiverContext was missing a remoteServiceName
  micrometer-observation/src/main/java/io/micrometer/observation/transport/ReceiverContext.java
Labels: enhancement

#3422 Upgrade to me.champeau.mrjar 0.1.1
  micrometer-core/build.gradle
  micrometer-test/build.gradle
Labels: build, dependency-upgrade

#3421 Polish "JDK11 HttpClient instrumentation"
  README.md
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/ObservationOrTimerCompatibleInstrumentation.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/HttpClientObservationConvention.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClient.java
  micrometer-core/src/test/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClientTests.java
  micrometer-test/src/test/java11/io/micrometer/core/instrument/JdkHttpClientTimingInstrumentationVerificationTests.java
Labels: polish

#3417 Polish "Apache HTTP client instrumentation with Observation"
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/ApacheHttpClientDocumentedObservation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/DefaultApacheHttpClientObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/HttpContextUtils.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: polish

#3423 Make observation return its context and immutable access to parent
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationView.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTests.java
Labels: enhancement, module: micrometer-observation

#3418 Handle IO_ERROR for Apache HTTP client with observation API
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/DefaultApacheHttpClientObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpRequestExecutorTest.java
Labels: enhancement, module: micrometer-core

#3424 Support message supplier in WarnThenDebugLogger
  implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v1/DynatraceNamingConventionV1.java
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxNamingConvention.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java
  micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/WarnThenDebugLogger.java
Labels: type: task

#3428 Polish Observation
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationConvention.java
Labels: polish

#3432 Added more assertions for TestObservationRegistry
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistryAssert.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/TestObservationRegistryAssertTests.java
Labels: enhancement, module: micrometer-observation-test

#3425 Polishing Observation API
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/DefaultApacheHttpClientObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/ObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/DocumentedObservation.java
  micrometer-observation/src/test/java/io/micrometer/observation/docs/DocumentedObservationTests.java
Labels: polish, breaking-change

#3431 Update OtlpMeterRegistryTest to run builds on Java 19
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpMeterRegistryTest.java
Labels: type: task

#3437 Update TagsTest to run builds on Java 19
  micrometer-core/src/test/java/io/micrometer/core/instrument/TagsTest.java
Labels: type: task

#3434 Update samples to use Spring Boot 2.7.4
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-spring-integration/build.gradle
Labels: type: task

#3435 Upgrade to JApicmp Gradle Plugin 0.4.1
  build.gradle
  buildscript-gradle.lockfile
Labels: type: task

#3438 Polish "HTTP server instrumentation TCK"
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JettyServerTimingInstrumentationVerificationTests.java
Labels: polish, module: micrometer-test

#3433 Add wrap functionality to the Observation
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
Labels: enhancement, module: micrometer-observation

#3441 Properly pin gradle-info-plugin to 11.4.1
  build.gradle
  buildscript-gradle.lockfile
Labels: build, dependency-upgrade

#3443 Take Supplier<Context> instead of Context
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/ObservationRequestEventListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/observation/ObservationOrTimerCompatibleInstrumentation.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryCompatibilityKit.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationContextAssertTests.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/aop/ObservedAspectObservationDocumentation.java
  micrometer-observation/src/main/java/io/micrometer/observation/docs/ObservationDocumentation.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationRegistryTest.java
  micrometer-observation/src/test/java/io/micrometer/observation/ObservationTests.java
  micrometer-observation/src/test/java/io/micrometer/observation/docs/ObservationDocumentationTests.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/ObservationHandlerSample.java
Labels: breaking-change, module: micrometer-observation
