Repository micrometer-metrics/micrometer, pull requests merged in 2022-10, with the labels that each got.

#3445 Exclude buildscript-gradle.lockfile in deleteLockFiles task
  build.gradle
Labels: type: task, build

#3446 Polish "Tck with observations"
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpRequestTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyKeyValues.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/ObservationRequestEventListener.java
Labels: polish

#3451 Consistently mark ObservationRegistry parameters not null
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
Labels: polish, module: micrometer-observation

#3447 StatsdMeterRegistryPublishTest fails randomly.
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
Labels: bug

#3455 Bump to a medium+ resource class for CI builds
  .circleci/config.yml
Labels: type: task

#3454 Allow documenting optional keys
  micrometer-commons/src/main/java/io/micrometer/common/docs/KeyName.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/TestObservationRegistryAssertTests.java
Labels: enhancement, module: micrometer-common

#3372 Test against ObservationDocumentation in instrumentation TCK
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/ApacheHttpClientObservationDocumentation.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/InstrumentationTimingVerificationTests.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/InstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/ApacheHttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/JerseyServerTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/OkHttpClientTimingInstrumentationVerificationTests.java
  micrometer-test/src/test/java11/io/micrometer/core/instrument/binder/jdk/JdkHttpClientTimingInstrumentationVerificationTests.java
Labels: enhancement, module: micrometer-test

#3459 Upgrade Spring Java Format dependencies to 0.0.35
  benchmarks/benchmarks-core/gradle.lockfile
  build.gradle
  buildscript-gradle.lockfile
  implementations/micrometer-registry-appoptics/gradle.lockfile
  implementations/micrometer-registry-atlas/gradle.lockfile
  implementations/micrometer-registry-azure-monitor/gradle.lockfile
  implementations/micrometer-registry-cloudwatch/gradle.lockfile
  implementations/micrometer-registry-cloudwatch2/gradle.lockfile
  implementations/micrometer-registry-datadog/gradle.lockfile
  implementations/micrometer-registry-dynatrace/gradle.lockfile
  implementations/micrometer-registry-elastic/gradle.lockfile
  implementations/micrometer-registry-ganglia/gradle.lockfile
  implementations/micrometer-registry-graphite/gradle.lockfile
  implementations/micrometer-registry-health/gradle.lockfile
  implementations/micrometer-registry-humio/gradle.lockfile
  implementations/micrometer-registry-influx/gradle.lockfile
  implementations/micrometer-registry-jmx/gradle.lockfile
  implementations/micrometer-registry-kairos/gradle.lockfile
  implementations/micrometer-registry-new-relic/gradle.lockfile
  implementations/micrometer-registry-opentsdb/gradle.lockfile
  implementations/micrometer-registry-prometheus/gradle.lockfile
  implementations/micrometer-registry-signalfx/gradle.lockfile
  implementations/micrometer-registry-stackdriver/gradle.lockfile
  implementations/micrometer-registry-statsd/gradle.lockfile
  implementations/micrometer-registry-wavefront/gradle.lockfile
  micrometer-core/gradle.lockfile
  micrometer-jersey2/gradle.lockfile
  micrometer-test/gradle.lockfile
  samples/micrometer-samples-boot2-reactive/gradle.lockfile
  samples/micrometer-samples-boot2/gradle.lockfile
  samples/micrometer-samples-core/gradle.lockfile
  samples/micrometer-samples-hazelcast/gradle.lockfile
  samples/micrometer-samples-hazelcast3/gradle.lockfile
  samples/micrometer-samples-javalin/gradle.lockfile
  samples/micrometer-samples-jersey3/gradle.lockfile
  samples/micrometer-samples-spring-integration/gradle.lockfile
Labels: build, dependency-upgrade

#3481 Disable downloadBaseline task for micrometer-jetty11
  build.gradle
  micrometer-jetty11/build.gradle
Labels: type: task

#3480 Polish TestObservationRegistryAssert changes
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistryAssert.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/TestObservationRegistryAssertTests.java
Labels: polish

#3482 Fix Javadoc errors
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistryAssert.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpClientTimingInstrumentationVerificationTests.java
Labels: polish

#3488 Polish "Add Observation instrumentation for gRPC client and server"
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/ObservationGrpcClientCallListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/ObservationGrpcServerCallListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/ObservationGrpcServerInterceptor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/grpc/GrpcObservationTest.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/GrpcObservationSample.java
Labels: polish, module: micrometer-core

#3495 Fix failure message in ObservationContextAssert.hasSubsetOfKeys()
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationContextAssertTests.java
Labels: bug

#3498 Polish "Jetty 11 module"
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/DefaultHttpJakartaServletRequestTagsProvider.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/http/HttpRequestTags.java
Labels: polish, module: jetty11

#3500 Added remoteServiceAddress for Sender / Receiver contexts
  micrometer-observation/src/main/java/io/micrometer/observation/transport/ReceiverContext.java
  micrometer-observation/src/main/java/io/micrometer/observation/transport/SenderContext.java
Labels: enhancement

#3501 Update CircleCI OpenJDK images to 8.0.345 and 11.0.16 respectively
  .circleci/config.yml
Labels: type: task, build

#3504 Verify sender propagation for HTTP client instrumentation
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpClientTimingInstrumentationVerificationTests.java
Labels: enhancement, module: micrometer-test

#3503 Add support for creating KeyValues from any iterable
  micrometer-commons/src/main/java/io/micrometer/common/KeyValue.java
  micrometer-commons/src/main/java/io/micrometer/common/KeyValues.java
  micrometer-commons/src/test/java/io/micrometer/common/KeyValuesTest.java
Labels: enhancement, module: micrometer-common

#3507 Verify sender propagation for HTTP server instrumentation
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyContext.java
  micrometer-test/src/main/java/io/micrometer/core/instrument/HttpServerTimingInstrumentationVerificationTests.java
Labels: type: task, module: micrometer-test
