Repository micrometer-metrics/micrometer, pull requests merged in 2023-06, with the labels that each got.

#3876 Polish "Improve Otlp Delta Aggregation with support for max and Histogram"
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpStepDistributionSummary.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpStepTimer.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/StepMax.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpCumulativeMeterRegistryTest.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpDeltaMeterRegistryCompatibilityTest.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpDeltaMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractDistributionSummary.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeDistributionSummary.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/StepBucketHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowFixedBoundaryHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepValue.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/distribution/StepHistogramTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
Labels: polish

#3909 Polish "Publish values on close in OTLP registry"
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpStepBucketHistogram.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpStepTuple2.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpDeltaMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepTuple2.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepValue.java
Labels: polish

#3912 Polish "Fix observation scope handlings in grpc server instrumentation"
  config/checkstyle/checkstyle.xml
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/grpc/GrpcAsyncTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/grpc/GrpcObservationTest.java
Labels: polish

#3915 Replace ArgumentCaptor with assertArg()
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
Labels: polish, registry: dynatrace

#3918 Upgrade to me.champeau.jmh 0.7.1
  benchmarks/benchmarks-core/build.gradle
Labels: type: task

#3917 Upgrade to com.github.johnrengelman.shadow 8.1.1
  implementations/micrometer-registry-statsd/build.gradle
Labels: type: task, build

#3928 Upgrade to Spotless Gradle plugin 6.19.0
  build.gradle
  buildscript-gradle.lockfile
Labels: type: task, build

#3936 Polish "Introduces NullObservation"
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/contextpropagation/ObservationThreadLocalAccessor.java
  micrometer-observation/src/test/java/io/micrometer/observation/contextpropagation/ObservationThreadLocalAccessorTests.java
Labels: polish, module: micrometer-observation

#3947 NoOpRegistry and NoOpObservation respect scopes
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java
  micrometer-observation/src/main/java/io/micrometer/observation/NoopObservationRegistry.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java
  micrometer-observation/src/test/java/io/micrometer/observation/NoopObservationRegistryTests.java
Labels: bug
