Repository micrometer-metrics/micrometer, pull requests merged in 2023-09, with the labels that each got.

#4055 Suppress unchecked warning in StepFunctionCounterTest.closingRolloverPartialStep()
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepFunctionCounterTest.java
Labels: polish

#4057 Upgrade to Kotlin 1.7.21
  micrometer-core/build.gradle
  micrometer-core/gradle.lockfile
Labels: build, dependency-upgrade

#4041 Added example of integration with retrofit and okhttp
  dependencies.gradle
  micrometer-core/build.gradle
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationInterceptorTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/RetrofitOkHttpObservationInterceptorTest.java
Labels: type: task, module: micrometer-binders

#4036 Upgrade to Gradle Wrapper 8.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: type: task, build

#4087 Polish gh-4007
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/DefaultJmsProcessObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/DefaultJmsPublishObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/JmsInstrumentation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/JmsObservationDocumentation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/JmsProcessObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/JmsPublishObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/MessageConsumerInvocationHandler.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/MessageProducerInvocationHandler.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jms/SessionInvocationHandler.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/binder/jms/JmsInstrumentationTests.java
Labels: polish

#4083 Polish gh-3985
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
Labels: polish, registry: dynatrace

#4085 Replace deprecated ContextSnapshot.captureAllUsing()
  micrometer-core/src/main/java/io/micrometer/core/instrument/kotlin/KotlinObservationContextElement.java
  micrometer-observation/src/test/java/io/micrometer/observation/aop/ObservedAspectTests.java
  micrometer-observation/src/test/java/io/micrometer/observation/contextpropagation/ObservationThreadLocalAccessorTests.java
Labels: polish

#4086 Polish gh-4006
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
Labels: polish

#4098 Upgrade samples to Spring Boot 2.7.16
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2-reactive/gradle.lockfile
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-boot2/gradle.lockfile
  samples/micrometer-samples-spring-integration/build.gradle
  samples/micrometer-samples-spring-integration/gradle.lockfile
Labels: type: task

#4099 Polish Javadoc for gh-4034
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
  micrometer-observation/src/main/java/io/micrometer/observation/SimpleEvent.java
Labels: polish
