Repository micrometer-metrics/micrometer, pull requests merged in 2024-11, with the labels that each got.

#5641 Add docs for multiple MeterTag annotations
  docs/modules/ROOT/pages/concepts/counters.adoc
  docs/modules/ROOT/pages/concepts/timers.adoc
  docs/src/test/java/io/micrometer/docs/metrics/CountedAspectTest.java
  docs/src/test/java/io/micrometer/docs/metrics/TimedAspectTest.java
  samples/micrometer-samples-spring-framework6/src/test/java/io/micrometer/samples/spring6/aop/CountedAspectTest.java
  samples/micrometer-samples-spring-framework6/src/test/java/io/micrometer/samples/spring6/aop/TimedAspectTest.java
Labels: doc-update

#5654 Add CI build for JDK 23
  .circleci/config.yml
Labels: type: task

#5656 Upgrade machine-executor to ubuntu-2404:2024.08.1
  .circleci/config.yml
Labels: type: task, build

#5601 Enable Gauge builders to take a subclass of Number
  micrometer-core/src/main/java/io/micrometer/core/instrument/Gauge.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MultiGauge.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/TimeGauge.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/MultiGaugeTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/simple/SimpleMeterRegistryTest.java
Labels: enhancement, module: micrometer-core

#5663 Remove obsolete .gitattributes
  .gitattributes
Labels: type: task

#5652 Use BOM for Micrometer dependency examples in reference docs
  docs/modules/ROOT/pages/contextpropagation/installing.adoc
  docs/modules/ROOT/pages/implementations/_install.adoc
  docs/modules/ROOT/pages/implementations/datadog.adoc
  docs/modules/ROOT/pages/implementations/influx.adoc
  docs/modules/ROOT/pages/installing.adoc
  docs/modules/ROOT/pages/observation/installing.adoc
  docs/modules/ROOT/pages/observation/testing.adoc
Labels: doc-update, type: task

#5692 Polish gh-4959
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/KeyValuesMergeBenchmark.java
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/TagsMergeBenchmark.java
  micrometer-commons/src/main/java/io/micrometer/common/KeyValues.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Tags.java
Labels: polish

#5695 Upgrade to Gradle Wrapper 8.11.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task, build

#5693 Remove contextpropagation.adoc
  docs/modules/ROOT/pages/contextpropagation.adoc
  docs/modules/ROOT/pages/observation/instrumenting.adoc
Labels: doc-update

#5694 Polish gh-4955
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/StepBucketHistogram.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/distribution/FixedBoundaryHistogramTest.java
Labels: polish, module: micrometer-core

#5708 Polish
  build.gradle
  docs/modules/ROOT/pages/implementations/otlp.adoc
  docs/modules/ROOT/pages/implementations/prometheus.adoc
  docs/modules/ROOT/pages/reference/jetty.adoc
  implementations/micrometer-registry-otlp/build.gradle
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpConfigTest.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheusmetrics/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheusmetrics/PrometheusMeterRegistryIntegrationTest.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server/JerseyTags.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyConnectionMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/InvalidConfigurationException.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/hc5/ObservationExecChainHandlerIntegrationTest.java
  micrometer-java11/build.gradle
  micrometer-java11/src/main/java/io/micrometer/java11/instrument/binder/jdk/DefaultHttpClientObservationConvention.java
  micrometer-java11/src/main/java/io/micrometer/java11/instrument/binder/jdk/MicrometerHttpClient.java
  micrometer-jetty12/build.gradle
  micrometer-observation/src/main/java/io/micrometer/observation/aop/ObservedAspectObservationDocumentation.java
  micrometer-test/src/test/java/io/micrometer/core/instrument/ApacheAsyncHttpClientTimingInstrumentationVerificationTests.java
Labels: polish

#5707 Polish
  docs/modules/ROOT/pages/concepts/meter-provider.adoc
  docs/modules/ROOT/pages/reference/netty.adoc
  implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxNamingConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
  micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/DefaultJmsProcessObservationConvention.java
  micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/DefaultJmsPublishObservationConvention.java
Labels: polish

#5696 Use failWithActualExpectedAndMessage() where possible
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationContextAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/ObservationRegistryAssert.java
  micrometer-observation-test/src/main/java/io/micrometer/observation/tck/TestObservationRegistryAssert.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationContextAssertTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/ObservationRegistryAssertTests.java
  micrometer-observation-test/src/test/java/io/micrometer/observation/tck/TestObservationRegistryAssertTests.java
Labels: enhancement, module: micrometer-observation-test

#5698 Upgrade opentelemetry-proto to 1.4.0-alpha
  gradle/libs.versions.toml
Labels: dependency-upgrade, registry: otlp

#5710 Polish KafkaMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
Labels: polish

#5711 Use String.toLowerCase()/toUpperCase() with Locale.ROOT consistently
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/core/DefaultLongTaskTimerBenchmark.java
  config/checkstyle/checkstyle.xml
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-datadog/src/test/java/io/micrometer/datadog/DatadogMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v1/DynatraceMetricDefinition.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaMeterRegistry.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxApiVersion.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java
  implementations/micrometer-registry-influx/src/test/java/io/micrometer/influx/InfluxMeterRegistryVersionsTest.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsAgentClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsApiClientProvider.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/JooqExecuteListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommand.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/DurationValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/TimeUtils.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommandTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/FileDescriptorMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
Labels: enhancement

#3512 Add peer name and port to gRPC observation contexts
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/DefaultGrpcClientObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/DefaultGrpcServerObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/GrpcClientObservationContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/GrpcClientObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/GrpcObservationDocumentation.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/GrpcServerObservationContext.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/GrpcServerObservationConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/ObservationGrpcClientInterceptor.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/ObservationGrpcServerInterceptor.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/grpc/GrpcObservationTest.java
Labels: enhancement, module: micrometer-core
