Repository micrometer-metrics/micrometer, pull requests merged in 2025-04, with the labels that each got.

#6075 Delete deprecated JDK 11 classes
  micrometer-core/build.gradle
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/DefaultHttpClientObservationConvention.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/HttpClientContext.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/HttpClientObservationConvention.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/HttpClientObservationDocumentation.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClient.java
  micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/package-info.java
  micrometer-core/src/test/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClientTests.java
  micrometer-test/build.gradle
  micrometer-test/src/test/java11/io/micrometer/java11/instrument/binder/jdk/JdkHttpClientTimingInstrumentationVerificationTests.java
Labels: type: task, release notes, build, module: micrometer-core, breaking-change

#6070 Log warning about "function" meter re-registration
  docs/modules/ROOT/pages/concepts/counters.adoc
  docs/modules/ROOT/pages/concepts/gauges.adoc
  docs/modules/ROOT/pages/concepts/timers.adoc
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
Labels: bug, module: micrometer-core

#6076 Polish KafkaMetrics
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
Labels: polish, module: micrometer-core, instrumentation

#6080 Replace global dependency management with version catalog
  build.gradle
  dependencies.gradle
  docs/build.gradle
  gradle/libs.versions.toml
  implementations/micrometer-registry-appoptics/build.gradle
  implementations/micrometer-registry-atlas/build.gradle
  implementations/micrometer-registry-azure-monitor/build.gradle
  implementations/micrometer-registry-cloudwatch2/build.gradle
  implementations/micrometer-registry-datadog/build.gradle
  implementations/micrometer-registry-dynatrace/build.gradle
  implementations/micrometer-registry-elastic/build.gradle
  implementations/micrometer-registry-ganglia/build.gradle
  implementations/micrometer-registry-graphite/build.gradle
  implementations/micrometer-registry-health/build.gradle
  implementations/micrometer-registry-humio/build.gradle
  implementations/micrometer-registry-influx/build.gradle
  implementations/micrometer-registry-jmx/build.gradle
  implementations/micrometer-registry-kairos/build.gradle
  implementations/micrometer-registry-new-relic/build.gradle
  implementations/micrometer-registry-opentsdb/build.gradle
  implementations/micrometer-registry-otlp/build.gradle
  implementations/micrometer-registry-prometheus/build.gradle
  implementations/micrometer-registry-signalfx/build.gradle
  implementations/micrometer-registry-statsd/build.gradle
  implementations/micrometer-registry-wavefront/build.gradle
  micrometer-commons/build.gradle
  micrometer-core/build.gradle
  micrometer-jakarta9/build.gradle
  micrometer-java11/build.gradle
  micrometer-java21/build.gradle
  micrometer-jetty11/build.gradle
  micrometer-jetty12/build.gradle
  micrometer-observation-test/build.gradle
  micrometer-observation/build.gradle
  micrometer-osgi-test/build.gradle
  micrometer-test/build.gradle
  samples/micrometer-samples-core/build.gradle
  samples/micrometer-samples-hazelcast/build.gradle
  samples/micrometer-samples-hazelcast3/build.gradle
  samples/micrometer-samples-javalin/build.gradle
  samples/micrometer-samples-jersey3/build.gradle
  samples/micrometer-samples-jooq/build.gradle
  samples/micrometer-samples-kotlin/build.gradle
  samples/micrometer-samples-spring-framework6/build.gradle
Labels: type: task, build

#6092 Replace deprecated Project.task()
  build.gradle
  docs/src/test/resources/docs-generator-build.gradle
  implementations/micrometer-registry-stackdriver/build.gradle
  micrometer-core/build.gradle
Labels: type: task, build

#6119 Add assertion for no re-registering Kafka metrics
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/testsupport/system/CapturedOutput.java
  micrometer-core/src/test/java/io/micrometer/core/testsupport/system/OutputCapture.java
  micrometer-core/src/test/java/io/micrometer/core/testsupport/system/OutputCaptureExtension.java
  micrometer-core/src/test/java/io/micrometer/core/testsupport/system/package-info.java
Labels: type: task, instrumentation

#6126 Add test for unsuccessful OtlpHttpMetricsSender.send()
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpHttpMetricsSenderTests.java
Labels: type: task, registry: otlp

#6137 Fix CaffeineCacheMetricsTest.doNotReportMetricsForNonLoadingCache()
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/CaffeineCacheMetricsTest.java
Labels: type: task

#6142 Suppress Error Prone warnings from generated code
  build.gradle
Labels: type: task, build

#6138 (docs): add document for JMS instrumentation
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/reference/jms.adoc
Labels: doc-update

#6144 Remove obsolete deprecation warning suppression
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMetricConverter.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpMeterRegistryTest.java
Labels: type: task

#6147 Replace Meter.Id.getTags() with cheaper alternatives
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Meter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java
Labels: enhancement, performance

#6143 Resolve MissingOverride warnings from Error Prone
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaConfig.java
  implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteConfig.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
  implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosConfig.java
  implementations/micrometer-registry-opentsdb/src/main/java/io/micrometer/opentsdb/OpenTSDBConfig.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpCumulativeMeterRegistryTest.java
  implementations/micrometer-registry-otlp/src/test/java/io/micrometer/registry/otlp/OtlpDeltaMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/composite/AbstractCompositeMeter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/cumulative/CumulativeFunctionTimer.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepFunctionTimer.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/cache/GuavaCacheMetricsTest.java
  micrometer-observation/src/main/java/io/micrometer/observation/Observation.java
Labels: polish

#6150 Remove Hazelcast 3 tests
  gradle/libs.versions.toml
  samples/micrometer-samples-hazelcast3/build.gradle
  samples/micrometer-samples-hazelcast3/src/main/java/io/micrometer/samples/hazelcast3/HazelcastCacheSample.java
  samples/micrometer-samples-hazelcast3/src/main/resources/logback.xml
  samples/micrometer-samples-hazelcast3/src/test/java/io/micrometer/samples/hazelcast3/Hazelcast3CacheMetricsCompatibilityTest.java
  samples/micrometer-samples-hazelcast3/src/test/java/io/micrometer/samples/hazelcast3/Hazelcast3CacheMetricsTest.java
  settings.gradle
Labels: type: task

#6151 Polish
  docs/modules/ROOT/pages/concepts/counters.adoc
  docs/modules/ROOT/pages/concepts/timers.adoc
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorConfig.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceMeterRegistryTest.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMetricConverter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/Meter.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepFunctionTimer.java
  micrometer-observation/src/test/java/io/micrometer/observation/aop/HighCardinalityAnnotationHandler.java
Labels: type: task, polish

#6149 Remove Spring Boot 2 samples
  gradle/libs.versions.toml
  samples/micrometer-samples-boot2-reactive/build.gradle
  samples/micrometer-samples-boot2-reactive/src/main/java/io/micrometer/boot2/reactive/samples/PrometheusSample.java
  samples/micrometer-samples-boot2-reactive/src/main/resources/application.yml
  samples/micrometer-samples-boot2/build.gradle
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/AppOpticsSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/AtlasSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/AzureMonitorSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/DatadogSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/DynatraceSampleV1.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/DynatraceSampleV2.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/ElasticSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/GangliaSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/HumioSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/InfluxSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/JmxSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/KairosSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/LoggingRegistrySample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/NewRelicSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/PrometheusPushgatewaySample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/PrometheusSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/SignalFxSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/SimpleSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/StackdriverSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/StatsdDatadogSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/StatsdEtsySample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/StatsdTelegrafSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/WavefrontSample.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/HttpMetricsTagConfiguration.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/Person.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/PersonController.java
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/ServiceLevelObjectiveConfiguration.java
  samples/micrometer-samples-boot2/src/main/resources/.gitignore
  samples/micrometer-samples-boot2/src/main/resources/application-appoptics.yml
  samples/micrometer-samples-boot2/src/main/resources/application-atlas.yml
  samples/micrometer-samples-boot2/src/main/resources/application-azuremonitor.yml
  samples/micrometer-samples-boot2/src/main/resources/application-datadog.yml
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v1.yml
  samples/micrometer-samples-boot2/src/main/resources/application-dynatrace-v2.yml
  samples/micrometer-samples-boot2/src/main/resources/application-elastic.yml
  samples/micrometer-samples-boot2/src/main/resources/application-ganglia.yml
  samples/micrometer-samples-boot2/src/main/resources/application-humio.yml
  samples/micrometer-samples-boot2/src/main/resources/application-influx.yml
  samples/micrometer-samples-boot2/src/main/resources/application-jmx.yml
  samples/micrometer-samples-boot2/src/main/resources/application-kairos.yml
  samples/micrometer-samples-boot2/src/main/resources/application-prometheus-pushgateway.yml
  samples/micrometer-samples-boot2/src/main/resources/application-prometheus.yml
  samples/micrometer-samples-boot2/src/main/resources/application-signalfx.yml
  samples/micrometer-samples-boot2/src/main/resources/application-stackdriver.yml
  samples/micrometer-samples-boot2/src/main/resources/application-statsd-datadog.yml
  samples/micrometer-samples-boot2/src/main/resources/application-statsd-etsy.yml
  samples/micrometer-samples-boot2/src/main/resources/application-statsd-telegraf.yml
  samples/micrometer-samples-boot2/src/main/resources/application-wavefront.yml
  samples/micrometer-samples-boot2/src/main/resources/application.yml
  samples/micrometer-samples-boot2/src/main/resources/logback.xml
  samples/micrometer-samples-spring-integration/build.gradle
  samples/micrometer-samples-spring-integration/src/main/java/io/micrometer/spring/integration/samples/SpringIntegrationApplication.java
  settings.gradle
Labels: type: task

#6163 Remove redundant Checkstyle checks in favor of StringCaseLocaleUsage check from Error Prone
  config/checkstyle/checkstyle.xml
Labels: type: task, build

#6162 Resolve StringCaseLocaleUsage warnings from Error Prone
  implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java
  implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java
  implementations/micrometer-registry-datadog/src/test/java/io/micrometer/datadog/DatadogMeterRegistryTest.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v1/DynatraceMetricDefinition.java
  implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/v2/DynatraceExporterV2.java
  implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
  implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaMeterRegistry.java
  implementations/micrometer-registry-health/src/main/java/io/micrometer/health/ServiceLevelObjective.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxApiVersion.java
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java
  implementations/micrometer-registry-influx/src/test/java/io/micrometer/influx/InfluxMeterRegistryVersionsTest.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsAgentClientProvider.java
  implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicInsightsApiClientProvider.java
  implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java
  implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryTest.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/JooqExecuteListener.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommand.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/validate/DurationValidator.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/TimeUtils.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommandTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/FileDescriptorMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java
  micrometer-test/src/main/java/io/micrometer/core/tck/MeterRegistryCompatibilityKit.java
Labels: type: task, polish

#6173 Replace AssertionsForClassTypes with Assertions
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceDistributionSummaryTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/types/DynatraceTimerTest.java
  implementations/micrometer-registry-influx/src/test/java/io/micrometer/influx/InfluxMeterRegistryVersionsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ClassLoaderMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmCompilationMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/DiskSpaceMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/FileDescriptorMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/UptimeMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/config/NamingConventionTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepDistributionSummaryTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/step/StepTimerTest.java
Labels: polish

#6175 Handle StringCaseLocaleUsage as error
  build.gradle
Labels: type: task

#6177 Resolve DefaultCharset from Error Prone
  build.gradle
  docs/src/test/java/io/micrometer/docs/observation/messaging/ObservationMessagingIntegrationTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/DynatraceConfigTest.java
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
  implementations/micrometer-registry-new-relic/src/test/java/io/micrometer/newrelic/NewRelicMeterRegistryTest.java
  implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheusmetrics/PrometheusMeterRegistry.java
  implementations/micrometer-registry-prometheus/src/test/java/io/micrometer/prometheusmetrics/PrometheusMeterRegistryIntegrationTest.java
  implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/BufferingFlux.java
  micrometer-core/src/main/java/io/micrometer/core/ipc/http/HttpSender.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/util/IOUtilsTest.java
  micrometer-core/src/test/java/io/micrometer/core/testsupport/system/OutputCapture.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/utils/SampleRegistries.java
Labels: type: task, polish

#6176 Upgrade to Gradle Wrapper 8.14
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type: task, build

#6181 Use snapshot consistently in AppOpticsMeterRegistry.writeSummary()
  implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsMeterRegistry.java
Labels: bug, registry: appoptics
