Repository micrometer-metrics/micrometer, pull requests merged in 2025-06, with the labels that each got.

#6125 Add KeyName.withNoneValue()
  micrometer-commons/src/main/java/io/micrometer/common/docs/KeyName.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/hc5/DefaultApacheHttpClientObservationConvention.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/hc5/DefaultApacheHttpClientObservationConventionTest.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/httpcomponents/hc5/ObservationExecChainHandlerTest.java
Labels: enhancement, module: micrometer-observation

#6362 Upgrade to Gradle Wrapper 8.14.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: task, build

#6271 Resolve StringSplitter from Error Prone
  build.gradle
  implementations/micrometer-registry-dynatrace/src/test/java/io/micrometer/dynatrace/v2/DynatraceExporterV2Test.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java
Labels: type: task, polish

#6449 Use String.replace() where possible
  implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxNamingConvention.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java
  micrometer-core/src/main/java/io/micrometer/core/instrument/util/HierarchicalNameMapper.java
Labels: enhancement, performance

#6448 Resolve CatchAndPrintStackTrace from Error Prone
  build.gradle
  samples/micrometer-samples-boot2/src/main/java/io/micrometer/boot2/samples/components/PersonController.java
Labels: type: task

#6454 Suppress CollectionUndefinedEquality and DoNotCallSuggester from Error Prone
  build.gradle
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/grpc/GrpcAsyncTest.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/utils/SampleRegistries.java
Labels: type: task

#6468 Remove Dropwizard 5 usage
  benchmarks/benchmarks-core/build.gradle
  benchmarks/benchmarks-core/src/jmh/java/io/micrometer/benchmark/compare/CompareCountersWithOtherLibraries.java
  gradle/libs.versions.toml
Labels: type: task

#6469 Make benchmark module require at least Java 17
  CONTRIBUTING.md
  benchmarks/benchmarks-core/build.gradle
Labels: type: task

#6472 Resolve Finally and suppress ModifyCollectionInEnhancedForLoop from Error Prone
  build.gradle
  micrometer-core/src/test/java/io/micrometer/core/instrument/binder/logging/LogbackMetricsGh2868Test.java
  samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/LongTaskTimerSample.java
Labels: type: task, polish

#6451 Declare default @Retention on @Incubating explicitly
  micrometer-core/src/main/java/io/micrometer/core/annotation/Incubating.java
Labels: type: task, polish

#6484 Resolve NarrowCalculation and OperatorPrecedence from Error Prone
  build.gradle
  micrometer-core/src/main/java/io/micrometer/core/instrument/Tags.java
  micrometer-core/src/test/java/io/micrometer/core/instrument/composite/CompositeMeterRegistryTest.java
Labels: type: task
